# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_report/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaReport
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_report,
      attributes_class: Grafana::Types::ReportAttributes,
      outputs: { id: :id },
      map: [:name, :recipients, :schedule],
      map_present: [:dashboards, :formats, :layout, :message, :org_id, :orientation, :reply_to],
      map_bool: [:include_dashboard_link, :include_table_csv]
  end
  module Grafana
    include GrafanaReport
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
