# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_connections_metrics_endpoint_scrape_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaConnectionsMetricsEndpointScrapeJob
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_connections_metrics_endpoint_scrape_job,
      attributes_class: Grafana::Types::ConnectionsMetricsEndpointScrapeJobAttributes,
      outputs: { id: :id },
      map: [:authentication_method, :name, :stack_id, :url],
      map_present: [:authentication_basic_password, :authentication_basic_username, :authentication_bearer_token]
  end
  module Grafana
    include GrafanaConnectionsMetricsEndpointScrapeJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
