# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class ConnectionsMetricsEndpointScrapeJobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :authentication_method, T::String
    attribute :name, T::String
    attribute :stack_id, T::String
    attribute :url, T::String
    attribute? :authentication_basic_password, T::String.optional
    attribute? :authentication_basic_username, T::String.optional
    attribute? :authentication_bearer_token, T::String.optional
  end
end
