# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaUser
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_user,
      attributes_class: Grafana::Types::UserAttributes,
      outputs: { id: :id },
      map: [:email, :password],
      map_present: [:login, :name],
      map_bool: [:is_admin]
  end
  module Grafana
    include GrafanaUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
