# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_oncall_outgoing_webhook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOncallOutgoingWebhook
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_oncall_outgoing_webhook,
      attributes_class: Grafana::Types::OncallOutgoingWebhookAttributes,
      outputs: { id: :id },
      map: [:name, :url],
      map_present: [:authorization_header, :data, :headers, :http_method, :integration_filter, :password, :team_id, :trigger_template, :trigger_type, :user],
      map_bool: [:forward_whole_payload, :is_webhook_enabled]
  end
  module Grafana
    include GrafanaOncallOutgoingWebhook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
