# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OncallOutgoingWebhookAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute :url, T::String
    attribute? :authorization_header, T::String.optional
    attribute? :data, T::String.optional
    attribute? :forward_whole_payload, T::Bool.optional
    attribute? :headers, T::String.optional
    attribute? :http_method, T::String.optional
    attribute? :integration_filter, T::Array.of(T::String).optional
    attribute? :is_webhook_enabled, T::Bool.optional
    attribute? :password, T::String.optional
    attribute? :team_id, T::String.optional
    attribute? :trigger_template, T::String.optional
    attribute? :trigger_type, T::String.optional
    attribute? :user, T::String.optional
  end
end
