# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_dashboard_public/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDashboardPublic
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_dashboard_public,
      attributes_class: Grafana::Types::DashboardPublicAttributes,
      outputs: { id: :id },
      map: [:dashboard_uid],
      map_present: [:org_id, :share],
      map_bool: [:annotations_enabled, :is_enabled, :time_selection_enabled]
  end
  module Grafana
    include GrafanaDashboardPublic
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
