# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_playlist/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaPlaylist
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_playlist,
      attributes_class: Grafana::Types::PlaylistAttributes,
      outputs: { id: :id },
      map: [:interval, :item, :name],
      map_present: [:org_id]
  end
  module Grafana
    include GrafanaPlaylist
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
