# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class DashboardAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :config_json, T::String
    attribute? :folder, T::String.optional
    attribute? :message, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :overwrite, T::Bool.optional
  end
end
