# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_access_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudAccessPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_access_policy,
      attributes_class: Grafana::Types::CloudAccessPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :realm, :region, :scopes],
      map_present: [:conditions, :display_name]
  end
  module Grafana
    include GrafanaCloudAccessPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
