# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_machine_learning_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaMachineLearningJob
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_machine_learning_job,
      attributes_class: Grafana::Types::MachineLearningJobAttributes,
      outputs: { id: :id },
      map: [:datasource_type, :datasource_uid, :metric, :name, :query_params],
      map_present: [:custom_labels, :description, :holidays, :hyper_params, :interval, :training_window]
  end
  module Grafana
    include GrafanaMachineLearningJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
