# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_k6_installation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaK6Installation
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_k6_installation,
      attributes_class: Grafana::Types::K6InstallationAttributes,
      outputs: { id: :id },
      map: [:cloud_access_policy_token, :grafana_sa_token, :grafana_user, :stack_id]
  end
  module Grafana
    include GrafanaK6Installation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
