# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class K6InstallationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :cloud_access_policy_token, T::String
    attribute :grafana_sa_token, T::String
    attribute :grafana_user, T::String
    attribute :stack_id, T::String
  end
end
