# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_service_account_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaServiceAccountToken
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_service_account_token,
      attributes_class: Grafana::Types::ServiceAccountTokenAttributes,
      outputs: { id: :id },
      map: [:name, :service_account_id],
      map_present: [:seconds_to_live]
  end
  module Grafana
    include GrafanaServiceAccountToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
