# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OrganizationPreferencesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute? :home_dashboard_uid, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :theme, T::String.optional
    attribute? :timezone, T::String.optional
    attribute? :week_start, T::String.optional
  end
end
