# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_provider_aws_resource_metadata_scrape_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudProviderAwsResourceMetadataScrapeJob
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_provider_aws_resource_metadata_scrape_job,
      attributes_class: Grafana::Types::CloudProviderAwsResourceMetadataScrapeJobAttributes,
      outputs: { id: :id },
      map: [:aws_account_resource_id, :name, :stack_id],
      map_present: [:service]
  end
  module Grafana
    include GrafanaCloudProviderAwsResourceMetadataScrapeJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
