# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_machine_learning_outlier_detector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaMachineLearningOutlierDetector
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_machine_learning_outlier_detector,
      attributes_class: Grafana::Types::MachineLearningOutlierDetectorAttributes,
      outputs: { id: :id },
      map: [:algorithm, :datasource_type, :datasource_uid, :metric, :name, :query_params],
      map_present: [:description, :interval]
  end
  module Grafana
    include GrafanaMachineLearningOutlierDetector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
