# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class MachineLearningOutlierDetectorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :algorithm, T::Array.of(T::Hash)
    attribute :datasource_type, T::String
    attribute :datasource_uid, T::String
    attribute :metric, T::String
    attribute :name, T::String
    attribute :query_params, T::Hash
    attribute? :description, T::String.optional
    attribute? :interval, T::Float.optional
  end
end
