# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_dashboard_permission/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDashboardPermission
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_dashboard_permission,
      attributes_class: Grafana::Types::DashboardPermissionAttributes,
      outputs: { id: :id },
      map_present: [:org_id, :permissions]
  end
  module Grafana
    include GrafanaDashboardPermission
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
