# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_access_policy_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudAccessPolicyToken
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_access_policy_token,
      attributes_class: Grafana::Types::CloudAccessPolicyTokenAttributes,
      outputs: { id: :id },
      map: [:access_policy_id, :name, :region],
      map_present: [:display_name, :expires_at]
  end
  module Grafana
    include GrafanaCloudAccessPolicyToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
