# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_synthetic_monitoring_check_alerts/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaSyntheticMonitoringCheckAlerts
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_synthetic_monitoring_check_alerts,
      attributes_class: Grafana::Types::SyntheticMonitoringCheckAlertsAttributes,
      outputs: { id: :id },
      map: [:alerts, :check_id]
  end
  module Grafana
    include GrafanaSyntheticMonitoringCheckAlerts
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
