# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class SyntheticMonitoringCheckAlertsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :alerts, T::Array.of(T::Hash)
    attribute :check_id, T::Float
  end
end
