# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class MachineLearningHolidayAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute? :custom_periods, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :ical_timezone, T::String.optional
    attribute? :ical_url, T::String.optional
  end
end
