# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_fleet_management_collector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFleetManagementCollector
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_fleet_management_collector,
      attributes_class: Grafana::Types::FleetManagementCollectorAttributes,
      outputs: { id: :id },
      map: [:id]
  end
  module Grafana
    include GrafanaFleetManagementCollector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
