# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class CloudPrivateDataSourceConnectNetworkTokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute :pdc_network_id, T::String
    attribute :region, T::String
    attribute? :display_name, T::String.optional
    attribute? :expires_at, T::String.optional
  end
end
