# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class RoleAssignmentItemAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :role_uid, T::String
    attribute? :service_account_id, T::String.optional
    attribute? :team_id, T::String.optional
    attribute? :user_id, T::String.optional
  end
end
