# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_data_source_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDataSourceConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_data_source_config,
      attributes_class: Grafana::Types::DataSourceConfigAttributes,
      outputs: { id: :id },
      map_present: [:http_headers, :json_data_encoded, :org_id, :secure_json_data_encoded]
  end
  module Grafana
    include GrafanaDataSourceConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
