# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class DataSourceConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute? :http_headers, T::Hash.optional
    attribute? :json_data_encoded, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :secure_json_data_encoded, T::String.optional
  end
end
