# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_k6_project/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaK6Project
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_k6_project,
      attributes_class: Grafana::Types::K6ProjectAttributes,
      outputs: { id: :id },
      map: [:name]
  end
  module Grafana
    include GrafanaK6Project
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
