# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_organization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOrganization
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_organization,
      attributes_class: Grafana::Types::OrganizationAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:admin_user, :admins, :editors, :users_without_access, :viewers],
      map_bool: [:create_users]
  end
  module Grafana
    include GrafanaOrganization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
