# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OrganizationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute? :admin_user, T::String.optional
    attribute? :admins, T::Array.of(T::String).optional
    attribute? :create_users, T::Bool.optional
    attribute? :editors, T::Array.of(T::String).optional
    attribute? :users_without_access, T::Array.of(T::String).optional
    attribute? :viewers, T::Array.of(T::String).optional
  end
end
