# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_oncall_escalation_chain/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOncallEscalationChain
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_oncall_escalation_chain,
      attributes_class: Grafana::Types::OncallEscalationChainAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:team_id]
  end
  module Grafana
    include GrafanaOncallEscalationChain
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
