# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_apps_dashboard_dashboard_v1beta1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaAppsDashboardDashboardV1beta1
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_apps_dashboard_dashboard_v1beta1,
      attributes_class: Grafana::Types::AppsDashboardDashboardV1beta1Attributes,
      outputs: { id: :id },
      map_present: [:metadata, :options, :spec]
  end
  module Grafana
    include GrafanaAppsDashboardDashboardV1beta1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
