# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class AnnotationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :text, T::String
    attribute? :dashboard_uid, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :panel_id, T::Float.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
