# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class LibraryPanelAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :model_json, T::String
    attribute :name, T::String
    attribute? :folder_uid, T::String.optional
    attribute? :org_id, T::String.optional
  end
end
