# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_team/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaTeam
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_team,
      attributes_class: Grafana::Types::TeamAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:email, :members, :org_id, :preferences, :team_sync],
      map_bool: [:ignore_externally_synced_members]
  end
  module Grafana
    include GrafanaTeam
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
