# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_synthetic_monitoring_installation/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaSyntheticMonitoringInstallation
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_synthetic_monitoring_installation,
      attributes_class: Grafana::Types::SyntheticMonitoringInstallationAttributes,
      outputs: { id: :id },
      map: [:metrics_publisher_key, :stack_id]
  end
  module Grafana
    include GrafanaSyntheticMonitoringInstallation
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
