# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class SyntheticMonitoringInstallationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :metrics_publisher_key, T::String
    attribute :stack_id, T::String
  end
end
