# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_folder_permission_item/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFolderPermissionItem
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_folder_permission_item,
      attributes_class: Grafana::Types::FolderPermissionItemAttributes,
      outputs: { id: :id },
      map: [:folder_uid, :permission],
      map_present: [:role, :team, :user]
  end
  module Grafana
    include GrafanaFolderPermissionItem
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
