# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_apps_playlist_playlist_v0alpha1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaAppsPlaylistPlaylistV0alpha1
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_apps_playlist_playlist_v0alpha1,
      attributes_class: Grafana::Types::AppsPlaylistPlaylistV0alpha1Attributes,
      outputs: { id: :id },
      map_present: [:metadata, :options, :spec]
  end
  module Grafana
    include GrafanaAppsPlaylistPlaylistV0alpha1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
