# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_data_source_permission/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDataSourcePermission
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_data_source_permission,
      attributes_class: Grafana::Types::DataSourcePermissionAttributes,
      outputs: { id: :id },
      map: [:datasource_uid],
      map_present: [:org_id, :permissions]
  end
  module Grafana
    include GrafanaDataSourcePermission
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
