# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_provider_azure_credential/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudProviderAzureCredential
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_provider_azure_credential,
      attributes_class: Grafana::Types::CloudProviderAzureCredentialAttributes,
      outputs: { id: :id },
      map: [:client_id, :client_secret, :name, :stack_id, :tenant_id],
      map_present: [:auto_discovery_configuration, :resource_discovery_tag_filter, :resource_tags_to_add_to_metrics]
  end
  module Grafana
    include GrafanaCloudProviderAzureCredential
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
