# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class CloudProviderAzureCredentialAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :client_id, T::String
    attribute :client_secret, T::String
    attribute :name, T::String
    attribute :stack_id, T::String
    attribute :tenant_id, T::String
    attribute? :auto_discovery_configuration, T::Array.of(T::Hash).optional
    attribute? :resource_discovery_tag_filter, T::Array.of(T::Hash).optional
    attribute? :resource_tags_to_add_to_metrics, T::Array.of(T::String).optional
  end
end
