# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_rule_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaRuleGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_rule_group,
      attributes_class: Grafana::Types::RuleGroupAttributes,
      outputs: { id: :id },
      map: [:folder_uid, :interval_seconds, :name, :rule],
      map_present: [:org_id],
      map_bool: [:disable_provenance]
  end
  module Grafana
    include GrafanaRuleGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
