# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class RuleGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :folder_uid, T::String
    attribute :interval_seconds, T::Float
    attribute :name, T::String
    attribute :rule, T::Array.of(T::Hash)
    attribute? :disable_provenance, T::Bool.optional
    attribute? :org_id, T::String.optional
  end
end
