# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaRole
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_role,
      attributes_class: Grafana::Types::RoleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :display_name, :group, :org_id, :permissions, :version],
      map_bool: [:auto_increment_version, :global, :hidden]
  end
  module Grafana
    include GrafanaRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
