# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class RoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute? :auto_increment_version, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :global, T::Bool.optional
    attribute? :group, T::String.optional
    attribute? :hidden, T::Bool.optional
    attribute? :org_id, T::String.optional
    attribute? :permissions, T::Array.of(T::Hash).optional
    attribute? :version, T::Float.optional
  end
end
