# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_folder_permission/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFolderPermission
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_folder_permission,
      attributes_class: Grafana::Types::FolderPermissionAttributes,
      outputs: { id: :id },
      map: [:folder_uid],
      map_present: [:org_id, :permissions]
  end
  module Grafana
    include GrafanaFolderPermission
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
