# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class K6ProjectLimitsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :project_id, T::String
    attribute? :duration_max_per_test, T::Float.optional
    attribute? :vu_browser_max_per_test, T::Float.optional
    attribute? :vu_max_per_test, T::Float.optional
    attribute? :vuh_max_per_month, T::Float.optional
  end
end
