# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_stack/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudStack
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_stack,
      attributes_class: Grafana::Types::CloudStackAttributes,
      outputs: { id: :id },
      map: [:name, :slug],
      map_present: [:description, :labels, :region_slug, :url, :wait_for_readiness_timeout],
      map_bool: [:wait_for_readiness]
  end
  module Grafana
    include GrafanaCloudStack
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
