# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class CloudStackAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute :slug, T::String
    attribute? :description, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :region_slug, T::String.optional
    attribute? :url, T::String.optional
    attribute? :wait_for_readiness, T::Bool.optional
    attribute? :wait_for_readiness_timeout, T::String.optional
  end
end
