# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_private_data_source_connect_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudPrivateDataSourceConnectNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_private_data_source_connect_network,
      attributes_class: Grafana::Types::CloudPrivateDataSourceConnectNetworkAttributes,
      outputs: { id: :id },
      map: [:name, :region, :stack_identifier],
      map_present: [:display_name]
  end
  module Grafana
    include GrafanaCloudPrivateDataSourceConnectNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
