# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class CloudProviderAwsCloudwatchScrapeJobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :aws_account_resource_id, T::String
    attribute :name, T::String
    attribute :stack_id, T::String
    attribute? :custom_namespace, T::Array.of(T::Hash).optional
    attribute? :service, T::Array.of(T::Hash).optional
  end
end
