# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_oncall_schedule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOncallSchedule
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_oncall_schedule,
      attributes_class: Grafana::Types::OncallScheduleAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:ical_url_overrides, :ical_url_primary, :shifts, :slack, :team_id, :time_zone],
      map_bool: [:enable_web_overrides]
  end
  module Grafana
    include GrafanaOncallSchedule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
