# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OncallScheduleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute? :enable_web_overrides, T::Bool.optional
    attribute? :ical_url_overrides, T::String.optional
    attribute? :ical_url_primary, T::String.optional
    attribute? :shifts, T::Array.of(T::String).optional
    attribute? :slack, T::Array.of(T::Hash).optional
    attribute? :team_id, T::String.optional
    attribute? :time_zone, T::String.optional
  end
end
