# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_folder/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFolder
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_folder,
      attributes_class: Grafana::Types::FolderAttributes,
      outputs: { id: :id },
      map: [:title],
      map_present: [:org_id, :parent_folder_uid],
      map_bool: [:prevent_destroy_if_not_empty]
  end
  module Grafana
    include GrafanaFolder
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
