# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_service_account_permission_item/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaServiceAccountPermissionItem
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_service_account_permission_item,
      attributes_class: Grafana::Types::ServiceAccountPermissionItemAttributes,
      outputs: { id: :id },
      map: [:permission, :service_account_id],
      map_present: [:team, :user]
  end
  module Grafana
    include GrafanaServiceAccountPermissionItem
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
