# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class ServiceAccountPermissionItemAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :permission, T::String
    attribute :service_account_id, T::String
    attribute? :team, T::String.optional
    attribute? :user, T::String.optional
  end
end
