# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_mute_timing/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaMuteTiming
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_mute_timing,
      attributes_class: Grafana::Types::MuteTimingAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:intervals, :org_id],
      map_bool: [:disable_provenance]
  end
  module Grafana
    include GrafanaMuteTiming
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
