# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class MuteTimingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute? :disable_provenance, T::Bool.optional
    attribute? :intervals, T::Array.of(T::Hash).optional
    attribute? :org_id, T::String.optional
  end
end
