# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_fleet_management_pipeline/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFleetManagementPipeline
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_fleet_management_pipeline,
      attributes_class: Grafana::Types::FleetManagementPipelineAttributes,
      outputs: { id: :id },
      map: [:contents, :name]
  end
  module Grafana
    include GrafanaFleetManagementPipeline
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
