# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class SloAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :description, T::String
    attribute :destination_datasource, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :objectives, T::Array.of(T::Hash)
    attribute :query, T::Array.of(T::Hash)
    attribute? :alerting, T::Array.of(T::Hash).optional
    attribute? :folder_uid, T::String.optional
    attribute? :label, T::Array.of(T::Hash).optional
    attribute? :search_expression, T::String.optional
  end
end
