# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_oncall_on_call_shift/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOncallOnCallShift
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_oncall_on_call_shift,
      attributes_class: Grafana::Types::OncallOnCallShiftAttributes,
      outputs: { id: :id },
      map: [:duration, :name, :start, :type],
      map_present: [:by_day, :by_month, :by_monthday, :frequency, :interval, :level, :rolling_users, :start_rotation_from_user_index, :team_id, :time_zone, :until, :users, :week_start]
  end
  module Grafana
    include GrafanaOncallOnCallShift
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
