# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OncallOnCallShiftAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :duration, T::Float
    attribute :name, T::String
    attribute :start, T::String
    attribute :type, T::String
    attribute? :by_day, T::Array.of(T::String).optional
    attribute? :by_month, T::Array.of(T::Float).optional
    attribute? :by_monthday, T::Array.of(T::Float).optional
    attribute? :frequency, T::String.optional
    attribute? :interval, T::Float.optional
    attribute? :level, T::Float.optional
    attribute? :rolling_users, T::Array.of(T::Array.of(T::String)).optional
    attribute? :start_rotation_from_user_index, T::Float.optional
    attribute? :team_id, T::String.optional
    attribute? :time_zone, T::String.optional
    attribute? :until, T::String.optional
    attribute? :users, T::Array.of(T::String).optional
    attribute? :week_start, T::String.optional
  end
end
