# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_data_source_permission_item/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDataSourcePermissionItem
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_data_source_permission_item,
      attributes_class: Grafana::Types::DataSourcePermissionItemAttributes,
      outputs: { id: :id },
      map: [:datasource_uid, :permission],
      map_present: [:role, :team, :user]
  end
  module Grafana
    include GrafanaDataSourcePermissionItem
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
