# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_data_source/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaDataSource
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_data_source,
      attributes_class: Grafana::Types::DataSourceAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:access_mode, :basic_auth_username, :database_name, :http_headers, :json_data_encoded, :org_id, :private_data_source_connect_network_id, :secure_json_data_encoded, :url, :username],
      map_bool: [:basic_auth_enabled, :is_default]
  end
  module Grafana
    include GrafanaDataSource
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
