# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class DataSourceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute? :access_mode, T::String.optional
    attribute? :basic_auth_enabled, T::Bool.optional
    attribute? :basic_auth_username, T::String.optional
    attribute? :database_name, T::String.optional
    attribute? :http_headers, T::Hash.optional
    attribute? :is_default, T::Bool.optional
    attribute? :json_data_encoded, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :private_data_source_connect_network_id, T::String.optional
    attribute? :secure_json_data_encoded, T::String.optional
    attribute? :url, T::String.optional
    attribute? :username, T::String.optional
  end
end
