# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_role_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaRoleAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_role_assignment,
      attributes_class: Grafana::Types::RoleAssignmentAttributes,
      outputs: { id: :id },
      map: [:role_uid],
      map_present: [:org_id, :service_accounts, :teams, :users]
  end
  module Grafana
    include GrafanaRoleAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
