# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class RoleAssignmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :role_uid, T::String
    attribute? :org_id, T::String.optional
    attribute? :service_accounts, T::Array.of(T::String).optional
    attribute? :teams, T::Array.of(T::String).optional
    attribute? :users, T::Array.of(T::Float).optional
  end
end
