# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OncallUserNotificationRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :type, T::String
    attribute :user_id, T::String
    attribute? :duration, T::Float.optional
    attribute? :position, T::Float.optional
  end
end
