# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_scim_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaScimConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_scim_config,
      attributes_class: Grafana::Types::ScimConfigAttributes,
      outputs: { id: :id },
      map_present: [:org_id],
      map_bool: [:allow_non_provisioned_users, :enable_group_sync, :enable_user_sync]
  end
  module Grafana
    include GrafanaScimConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
