# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_notification_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaNotificationPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_notification_policy,
      attributes_class: Grafana::Types::NotificationPolicyAttributes,
      outputs: { id: :id },
      map: [:contact_point, :group_by],
      map_present: [:group_interval, :group_wait, :org_id, :policy, :repeat_interval],
      map_bool: [:disable_provenance]
  end
  module Grafana
    include GrafanaNotificationPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
