# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class NotificationPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :contact_point, T::String
    attribute :group_by, T::Array.of(T::String)
    attribute? :disable_provenance, T::Bool.optional
    attribute? :group_interval, T::String.optional
    attribute? :group_wait, T::String.optional
    attribute? :org_id, T::String.optional
    attribute? :policy, T::Array.of(T::Hash).optional
    attribute? :repeat_interval, T::String.optional
  end
end
