# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_provider_aws_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudProviderAwsAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_provider_aws_account,
      attributes_class: Grafana::Types::CloudProviderAwsAccountAttributes,
      outputs: { id: :id },
      map: [:regions, :role_arn, :stack_id]
  end
  module Grafana
    include GrafanaCloudProviderAwsAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
