# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class CloudProviderAwsAccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :regions, T::Array.of(T::String)
    attribute :role_arn, T::String
    attribute :stack_id, T::String
  end
end
