# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_cloud_org_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaCloudOrgMember
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_cloud_org_member,
      attributes_class: Grafana::Types::CloudOrgMemberAttributes,
      outputs: { id: :id },
      map: [:org, :role, :user]
  end
  module Grafana
    include GrafanaCloudOrgMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
