# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_contact_point/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaContactPoint
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_contact_point,
      attributes_class: Grafana::Types::ContactPointAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:alertmanager, :dingding, :discord, :email, :googlechat, :kafka, :line, :oncall, :opsgenie, :org_id, :pagerduty, :pushover, :sensugo, :slack, :sns, :teams, :telegram, :threema, :victorops, :webex, :webhook, :wecom],
      map_bool: [:disable_provenance]
  end
  module Grafana
    include GrafanaContactPoint
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
