# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_synthetic_monitoring_probe/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaSyntheticMonitoringProbe
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_synthetic_monitoring_probe,
      attributes_class: Grafana::Types::SyntheticMonitoringProbeAttributes,
      outputs: { id: :id },
      map: [:latitude, :longitude, :name, :region],
      map_present: [:labels],
      map_bool: [:disable_browser_checks, :disable_scripted_checks, :public]
  end
  module Grafana
    include GrafanaSyntheticMonitoringProbe
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
