# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_oncall_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaOncallIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_oncall_integration,
      attributes_class: Grafana::Types::OncallIntegrationAttributes,
      outputs: { id: :id },
      map: [:default_route, :name, :type],
      map_present: [:dynamic_labels, :labels, :team_id, :templates]
  end
  module Grafana
    include GrafanaOncallIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
