# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class OncallIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :default_route, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :type, T::String
    attribute? :dynamic_labels, T::Array.of(T::Hash).optional
    attribute? :labels, T::Array.of(T::Hash).optional
    attribute? :team_id, T::String.optional
    attribute? :templates, T::Array.of(T::Hash).optional
  end
end
