# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_sso_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaSsoSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_sso_settings,
      attributes_class: Grafana::Types::SsoSettingsAttributes,
      outputs: { id: :id },
      map: [:provider_name],
      map_present: [:ldap_settings, :oauth2_settings, :saml_settings]
  end
  module Grafana
    include GrafanaSsoSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
