# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class SsoSettingsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :provider_name, T::String
    attribute? :ldap_settings, T::Array.of(T::Hash).optional
    attribute? :oauth2_settings, T::Array.of(T::Hash).optional
    attribute? :saml_settings, T::Array.of(T::Hash).optional
  end
end
