# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_connections_metrics_endpoint_scrape_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaConnectionsMetricsEndpointScrapeJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { authentication_method: 'test-value', name: 'test-value', stack_id: 'test-value', url: 'test-value' } }

  describe ':grafana_connections_metrics_endpoint_scrape_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'test')
        validate_required_attributes(config, [:authentication_method, :name, :stack_id, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_connections_metrics_endpoint_scrape_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_connections_metrics_endpoint_scrape_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_connections_metrics_endpoint_scrape_job('test', required_attrs)

        expect(ref.id).to eq("${grafana_connections_metrics_endpoint_scrape_job.test.id}")
        expect(ref.enabled).to eq("${grafana_connections_metrics_endpoint_scrape_job.test.enabled}")
        expect(ref.scrape_interval_seconds).to eq("${grafana_connections_metrics_endpoint_scrape_job.test.scrape_interval_seconds}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'test')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('scrape_interval_seconds')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authentication_basic_password: 'test-value', authentication_basic_username: 'test-value', authentication_bearer_token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'full')
        expect(config).to have_key('authentication_basic_password')
        expect(config).to have_key('authentication_basic_username')
        expect(config).to have_key('authentication_bearer_token')
      end
    end

    context 'optional attributes' do
      it 'includes authentication_basic_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('opt', required_attrs.merge(authentication_basic_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'opt')
        expect(config).to have_key('authentication_basic_password')
      end

      it 'omits authentication_basic_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'minimal')
        expect(config).not_to have_key('authentication_basic_password')
      end
      it 'includes authentication_basic_username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('opt', required_attrs.merge(authentication_basic_username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'opt')
        expect(config).to have_key('authentication_basic_username')
      end

      it 'omits authentication_basic_username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'minimal')
        expect(config).not_to have_key('authentication_basic_username')
      end
      it 'includes authentication_bearer_token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('opt', required_attrs.merge(authentication_bearer_token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'opt')
        expect(config).to have_key('authentication_bearer_token')
      end

      it 'omits authentication_bearer_token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'minimal')
        expect(config).not_to have_key('authentication_bearer_token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:authentication_basic_password, :authentication_bearer_token]
        expect(sensitive_fields).to include(:authentication_basic_password)
        expect(sensitive_fields).to include(:authentication_bearer_token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_connections_metrics_endpoint_scrape_job', 'typed')
        expect(config['authentication_method']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['stack_id']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_connections_metrics_endpoint_scrape_job('first', required_attrs)
        synth.grafana_connections_metrics_endpoint_scrape_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_connections_metrics_endpoint_scrape_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_connections_metrics_endpoint_scrape_job,
    method: :grafana_connections_metrics_endpoint_scrape_job,
    required_attrs: { authentication_method: 'test-value', name: 'test-value', stack_id: 'test-value', url: 'test-value' },
    expected_outputs: [:id, :enabled, :scrape_interval_seconds],
    sensitive_fields: [:authentication_basic_password, :authentication_bearer_token],
    immutable_fields: [],
    boolean_fields: []
end
