# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_slo resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaSlo do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', destination_datasource: [{ 'key1' => 'val1' }], name: 'test-value', objectives: [{ 'key1' => 'val1' }], query: [{ 'key1' => 'val1' }] } }

  describe ':grafana_slo' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_slo', 'test')
        validate_required_attributes(config, [:description, :destination_datasource, :name, :objectives, :query])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_slo('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_slo)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_slo('test', required_attrs)

        expect(ref.id).to eq("${grafana_slo.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alerting: [{ 'key1' => 'val1' }], folder_uid: 'test-value', label: [{ 'key1' => 'val1' }], search_expression: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_slo', 'full')
        expect(config).to have_key('alerting')
        expect(config).to have_key('folder_uid')
        expect(config).to have_key('label')
        expect(config).to have_key('search_expression')
      end
    end

    context 'optional attributes' do
      it 'includes alerting when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('opt', required_attrs.merge(alerting: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'opt')
        expect(config).to have_key('alerting')
      end

      it 'omits alerting when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'minimal')
        expect(config).not_to have_key('alerting')
      end
      it 'includes folder_uid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('opt', required_attrs.merge(folder_uid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'opt')
        expect(config).to have_key('folder_uid')
      end

      it 'omits folder_uid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'minimal')
        expect(config).not_to have_key('folder_uid')
      end
      it 'includes label when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('opt', required_attrs.merge(label: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'opt')
        expect(config).to have_key('label')
      end

      it 'omits label when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'minimal')
        expect(config).not_to have_key('label')
      end
      it 'includes search_expression when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('opt', required_attrs.merge(search_expression: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'opt')
        expect(config).to have_key('search_expression')
      end

      it 'omits search_expression when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_slo', 'minimal')
        expect(config).not_to have_key('search_expression')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_slo', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['destination_datasource']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['objectives']).to be_a(Array)
        expect(config['query']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_slo('first', required_attrs)
        synth.grafana_slo('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_slo')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_slo,
    method: :grafana_slo,
    required_attrs: { description: 'test-value', destination_datasource: [{ 'key1' => 'val1' }], name: 'test-value', objectives: [{ 'key1' => 'val1' }], query: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
