# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_contact_point resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaContactPoint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_contact_point' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_contact_point', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_contact_point('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_contact_point)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_contact_point('test', required_attrs)

        expect(ref.id).to eq("${grafana_contact_point.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alertmanager: [{ 'key1' => 'val1' }], dingding: [{ 'key1' => 'val1' }], disable_provenance: true, discord: [{ 'key1' => 'val1' }], email: [{ 'key1' => 'val1' }], googlechat: [{ 'key1' => 'val1' }], kafka: [{ 'key1' => 'val1' }], line: [{ 'key1' => 'val1' }], oncall: [{ 'key1' => 'val1' }], opsgenie: [{ 'key1' => 'val1' }], org_id: 'test-value', pagerduty: [{ 'key1' => 'val1' }], pushover: [{ 'key1' => 'val1' }], sensugo: [{ 'key1' => 'val1' }], slack: [{ 'key1' => 'val1' }], sns: [{ 'key1' => 'val1' }], teams: [{ 'key1' => 'val1' }], telegram: [{ 'key1' => 'val1' }], threema: [{ 'key1' => 'val1' }], victorops: [{ 'key1' => 'val1' }], webex: [{ 'key1' => 'val1' }], webhook: [{ 'key1' => 'val1' }], wecom: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_contact_point', 'full')
        expect(config).to have_key('alertmanager')
        expect(config).to have_key('dingding')
        expect(config).to have_key('disable_provenance')
        expect(config).to have_key('discord')
        expect(config).to have_key('email')
        expect(config).to have_key('googlechat')
        expect(config).to have_key('kafka')
        expect(config).to have_key('line')
        expect(config).to have_key('oncall')
        expect(config).to have_key('opsgenie')
        expect(config).to have_key('org_id')
        expect(config).to have_key('pagerduty')
        expect(config).to have_key('pushover')
        expect(config).to have_key('sensugo')
        expect(config).to have_key('slack')
        expect(config).to have_key('sns')
        expect(config).to have_key('teams')
        expect(config).to have_key('telegram')
        expect(config).to have_key('threema')
        expect(config).to have_key('victorops')
        expect(config).to have_key('webex')
        expect(config).to have_key('webhook')
        expect(config).to have_key('wecom')
      end
    end

    context 'optional attributes' do
      it 'includes alertmanager when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(alertmanager: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('alertmanager')
      end

      it 'omits alertmanager when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('alertmanager')
      end
      it 'includes dingding when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(dingding: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('dingding')
      end

      it 'omits dingding when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('dingding')
      end
      it 'includes disable_provenance when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(disable_provenance: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('disable_provenance')
      end

      it 'omits disable_provenance when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('disable_provenance')
      end
      it 'includes discord when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(discord: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('discord')
      end

      it 'omits discord when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('discord')
      end
      it 'includes email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(email: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('email')
      end

      it 'omits email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('email')
      end
      it 'includes googlechat when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(googlechat: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('googlechat')
      end

      it 'omits googlechat when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('googlechat')
      end
      it 'includes kafka when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(kafka: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('kafka')
      end

      it 'omits kafka when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('kafka')
      end
      it 'includes line when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(line: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('line')
      end

      it 'omits line when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('line')
      end
      it 'includes oncall when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(oncall: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('oncall')
      end

      it 'omits oncall when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('oncall')
      end
      it 'includes opsgenie when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(opsgenie: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('opsgenie')
      end

      it 'omits opsgenie when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('opsgenie')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes pagerduty when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(pagerduty: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('pagerduty')
      end

      it 'omits pagerduty when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('pagerduty')
      end
      it 'includes pushover when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(pushover: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('pushover')
      end

      it 'omits pushover when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('pushover')
      end
      it 'includes sensugo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(sensugo: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('sensugo')
      end

      it 'omits sensugo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('sensugo')
      end
      it 'includes slack when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(slack: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('slack')
      end

      it 'omits slack when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('slack')
      end
      it 'includes sns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(sns: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('sns')
      end

      it 'omits sns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('sns')
      end
      it 'includes teams when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(teams: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('teams')
      end

      it 'omits teams when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('teams')
      end
      it 'includes telegram when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(telegram: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('telegram')
      end

      it 'omits telegram when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('telegram')
      end
      it 'includes threema when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(threema: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('threema')
      end

      it 'omits threema when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('threema')
      end
      it 'includes victorops when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(victorops: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('victorops')
      end

      it 'omits victorops when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('victorops')
      end
      it 'includes webex when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(webex: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('webex')
      end

      it 'omits webex when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('webex')
      end
      it 'includes webhook when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(webhook: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('webhook')
      end

      it 'omits webhook when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('webhook')
      end
      it 'includes wecom when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('opt', required_attrs.merge(wecom: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'opt')
        expect(config).to have_key('wecom')
      end

      it 'omits wecom when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_contact_point', 'minimal')
        expect(config).not_to have_key('wecom')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_provenance=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_provenance: val)
          synth.grafana_contact_point("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_contact_point', "bool_#{val}")
          expect(config['disable_provenance']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_contact_point', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_contact_point('first', required_attrs)
        synth.grafana_contact_point('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_contact_point')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_contact_point,
    method: :grafana_contact_point,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_provenance]
end
