# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_role', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_role('test', required_attrs)

        expect(ref.id).to eq("${grafana_role.test.id}")
        expect(ref.uid).to eq("${grafana_role.test.uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_role', 'test')
        expect(config).not_to have_key('uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_increment_version: true, description: 'test-value', display_name: 'test-value', global: true, group: 'test-value', hidden: true, org_id: 'test-value', permissions: [{ 'key1' => 'val1' }], version: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_role', 'full')
        expect(config).to have_key('auto_increment_version')
        expect(config).to have_key('description')
        expect(config).to have_key('display_name')
        expect(config).to have_key('global')
        expect(config).to have_key('group')
        expect(config).to have_key('hidden')
        expect(config).to have_key('org_id')
        expect(config).to have_key('permissions')
        expect(config).to have_key('version')
      end
    end

    context 'optional attributes' do
      it 'includes auto_increment_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(auto_increment_version: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('auto_increment_version')
      end

      it 'omits auto_increment_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('auto_increment_version')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes global when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(global: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('global')
      end

      it 'omits global when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('global')
      end
      it 'includes group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(group: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('group')
      end

      it 'omits group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('group')
      end
      it 'includes hidden when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(hidden: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('hidden')
      end

      it 'omits hidden when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('hidden')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes permissions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(permissions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('permissions')
      end

      it 'omits permissions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('permissions')
      end
      it 'includes version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('opt', required_attrs.merge(version: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'opt')
        expect(config).to have_key('version')
      end

      it 'omits version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role', 'minimal')
        expect(config).not_to have_key('version')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_increment_version=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_increment_version: val)
          synth.grafana_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_role', "bool_#{val}")
          expect(config['auto_increment_version']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts global=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(global: val)
          synth.grafana_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_role', "bool_#{val}")
          expect(config['global']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts hidden=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(hidden: val)
          synth.grafana_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_role', "bool_#{val}")
          expect(config['hidden']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_role', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role('first', required_attrs)
        synth.grafana_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_role,
    method: :grafana_role,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :uid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_increment_version, :global, :hidden]
end
