# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_integration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallIntegration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { default_route: [{ 'key1' => 'val1' }], name: 'test-value', type: 'test-value' } }

  describe ':grafana_oncall_integration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'test')
        validate_required_attributes(config, [:default_route, :name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_integration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_integration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_integration('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_integration.test.id}")
        expect(ref.link).to eq("${grafana_oncall_integration.test.link}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_integration', 'test')
        expect(config).not_to have_key('link')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dynamic_labels: [{ 'key1' => 'val1' }], labels: [{ 'key1' => 'val1' }], team_id: 'test-value', templates: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_integration', 'full')
        expect(config).to have_key('dynamic_labels')
        expect(config).to have_key('labels')
        expect(config).to have_key('team_id')
        expect(config).to have_key('templates')
      end
    end

    context 'optional attributes' do
      it 'includes dynamic_labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('opt', required_attrs.merge(dynamic_labels: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'opt')
        expect(config).to have_key('dynamic_labels')
      end

      it 'omits dynamic_labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'minimal')
        expect(config).not_to have_key('dynamic_labels')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('opt', required_attrs.merge(labels: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes team_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('opt', required_attrs.merge(team_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'opt')
        expect(config).to have_key('team_id')
      end

      it 'omits team_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'minimal')
        expect(config).not_to have_key('team_id')
      end
      it 'includes templates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('opt', required_attrs.merge(templates: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'opt')
        expect(config).to have_key('templates')
      end

      it 'omits templates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_integration', 'minimal')
        expect(config).not_to have_key('templates')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_integration', 'typed')
        expect(config['default_route']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_integration('first', required_attrs)
        synth.grafana_oncall_integration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_integration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_integration,
    method: :grafana_oncall_integration,
    required_attrs: { default_route: [{ 'key1' => 'val1' }], name: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :link],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
