# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_provider_aws_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudProviderAwsAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { regions: ['test-value'], role_arn: 'test-value', stack_id: 'test-value' } }

  describe ':grafana_cloud_provider_aws_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_account', 'test')
        validate_required_attributes(config, [:regions, :role_arn, :stack_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_aws_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_provider_aws_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_aws_account('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_provider_aws_account.test.id}")
        expect(ref.name).to eq("${grafana_cloud_provider_aws_account.test.name}")
        expect(ref.resource_id).to eq("${grafana_cloud_provider_aws_account.test.resource_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_account', 'test')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('resource_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_account', 'typed')
        expect(config['regions']).to be_a(Array)
        expect(config['role_arn']).to be_a(String)
        expect(config['stack_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_account('first', required_attrs)
        synth.grafana_cloud_provider_aws_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_provider_aws_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_provider_aws_account,
    method: :grafana_cloud_provider_aws_account,
    required_attrs: { regions: ['test-value'], role_arn: 'test-value', stack_id: 'test-value' },
    expected_outputs: [:id, :name, :resource_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
