# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_escalation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallEscalation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { escalation_chain_id: 'test-value', position: 3.14, type: 'test-value' } }

  describe ':grafana_oncall_escalation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'test')
        validate_required_attributes(config, [:escalation_chain_id, :position, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_escalation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_escalation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_escalation('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_escalation.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ action_to_trigger: 'test-value', duration: 3.14, group_to_notify: 'test-value', important: true, notify_if_time_from: 'test-value', notify_if_time_to: 'test-value', notify_on_call_from_schedule: 'test-value', notify_to_team_members: 'test-value', persons_to_notify: ['test-value'], persons_to_notify_next_each_time: ['test-value'], severity: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'full')
        expect(config).to have_key('action_to_trigger')
        expect(config).to have_key('duration')
        expect(config).to have_key('group_to_notify')
        expect(config).to have_key('important')
        expect(config).to have_key('notify_if_time_from')
        expect(config).to have_key('notify_if_time_to')
        expect(config).to have_key('notify_on_call_from_schedule')
        expect(config).to have_key('notify_to_team_members')
        expect(config).to have_key('persons_to_notify')
        expect(config).to have_key('persons_to_notify_next_each_time')
        expect(config).to have_key('severity')
      end
    end

    context 'optional attributes' do
      it 'includes action_to_trigger when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(action_to_trigger: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('action_to_trigger')
      end

      it 'omits action_to_trigger when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('action_to_trigger')
      end
      it 'includes duration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(duration: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('duration')
      end

      it 'omits duration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('duration')
      end
      it 'includes group_to_notify when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(group_to_notify: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('group_to_notify')
      end

      it 'omits group_to_notify when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('group_to_notify')
      end
      it 'includes important when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(important: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('important')
      end

      it 'omits important when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('important')
      end
      it 'includes notify_if_time_from when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(notify_if_time_from: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('notify_if_time_from')
      end

      it 'omits notify_if_time_from when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('notify_if_time_from')
      end
      it 'includes notify_if_time_to when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(notify_if_time_to: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('notify_if_time_to')
      end

      it 'omits notify_if_time_to when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('notify_if_time_to')
      end
      it 'includes notify_on_call_from_schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(notify_on_call_from_schedule: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('notify_on_call_from_schedule')
      end

      it 'omits notify_on_call_from_schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('notify_on_call_from_schedule')
      end
      it 'includes notify_to_team_members when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(notify_to_team_members: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('notify_to_team_members')
      end

      it 'omits notify_to_team_members when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('notify_to_team_members')
      end
      it 'includes persons_to_notify when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(persons_to_notify: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('persons_to_notify')
      end

      it 'omits persons_to_notify when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('persons_to_notify')
      end
      it 'includes persons_to_notify_next_each_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(persons_to_notify_next_each_time: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('persons_to_notify_next_each_time')
      end

      it 'omits persons_to_notify_next_each_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('persons_to_notify_next_each_time')
      end
      it 'includes severity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('opt', required_attrs.merge(severity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'opt')
        expect(config).to have_key('severity')
      end

      it 'omits severity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'minimal')
        expect(config).not_to have_key('severity')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts important=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(important: val)
          synth.grafana_oncall_escalation("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_oncall_escalation', "bool_#{val}")
          expect(config['important']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_escalation', 'typed')
        expect(config['escalation_chain_id']).to be_a(String)
        expect(config['position']).to be_a(Float)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_escalation('first', required_attrs)
        synth.grafana_oncall_escalation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_escalation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_escalation,
    method: :grafana_oncall_escalation,
    required_attrs: { escalation_chain_id: 'test-value', position: 3.14, type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:important]
end
