# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_k6_load_test resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaK6LoadTest do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project_id: 'test-value', script: 'test-value' } }

  describe ':grafana_k6_load_test' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_k6_load_test', 'test')
        validate_required_attributes(config, [:name, :project_id, :script])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_k6_load_test('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_k6_load_test)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_k6_load_test('test', required_attrs)

        expect(ref.id).to eq("${grafana_k6_load_test.test.id}")
        expect(ref.created).to eq("${grafana_k6_load_test.test.created}")
        expect(ref.updated).to eq("${grafana_k6_load_test.test.updated}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_k6_load_test', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('updated')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ baseline_test_run_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_k6_load_test', 'full')
        expect(config).to have_key('baseline_test_run_id')
      end
    end

    context 'optional attributes' do
      it 'includes baseline_test_run_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('opt', required_attrs.merge(baseline_test_run_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_load_test', 'opt')
        expect(config).to have_key('baseline_test_run_id')
      end

      it 'omits baseline_test_run_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_load_test', 'minimal')
        expect(config).not_to have_key('baseline_test_run_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_k6_load_test', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
        expect(config['script']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_load_test('first', required_attrs)
        synth.grafana_k6_load_test('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_k6_load_test')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_k6_load_test,
    method: :grafana_k6_load_test,
    required_attrs: { name: 'test-value', project_id: 'test-value', script: 'test-value' },
    expected_outputs: [:id, :created, :updated],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
