# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_machine_learning_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaMachineLearningJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { datasource_type: 'test-value', datasource_uid: 'test-value', metric: 'test-value', name: 'test-value', query_params: { 'key1' => 'val1' } } }

  describe ':grafana_machine_learning_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'test')
        validate_required_attributes(config, [:datasource_type, :datasource_uid, :metric, :name, :query_params])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_machine_learning_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_job('test', required_attrs)

        expect(ref.id).to eq("${grafana_machine_learning_job.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_labels: { 'key1' => 'val1' }, description: 'test-value', holidays: ['test-value'], hyper_params: { 'key1' => 'val1' }, interval: 3.14, training_window: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'full')
        expect(config).to have_key('custom_labels')
        expect(config).to have_key('description')
        expect(config).to have_key('holidays')
        expect(config).to have_key('hyper_params')
        expect(config).to have_key('interval')
        expect(config).to have_key('training_window')
      end
    end

    context 'optional attributes' do
      it 'includes custom_labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(custom_labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('custom_labels')
      end

      it 'omits custom_labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('custom_labels')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes holidays when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(holidays: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('holidays')
      end

      it 'omits holidays when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('holidays')
      end
      it 'includes hyper_params when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(hyper_params: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('hyper_params')
      end

      it 'omits hyper_params when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('hyper_params')
      end
      it 'includes interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(interval: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('interval')
      end

      it 'omits interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('interval')
      end
      it 'includes training_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('opt', required_attrs.merge(training_window: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'opt')
        expect(config).to have_key('training_window')
      end

      it 'omits training_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'minimal')
        expect(config).not_to have_key('training_window')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_job', 'typed')
        expect(config['datasource_type']).to be_a(String)
        expect(config['datasource_uid']).to be_a(String)
        expect(config['metric']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['query_params']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_job('first', required_attrs)
        synth.grafana_machine_learning_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_machine_learning_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_machine_learning_job,
    method: :grafana_machine_learning_job,
    required_attrs: { datasource_type: 'test-value', datasource_uid: 'test-value', metric: 'test-value', name: 'test-value', query_params: { 'key1' => 'val1' } },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
