# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_frontend_o11y_app resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaFrontendO11yApp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { allowed_origins: ['test-value'], extra_log_attributes: { 'key1' => 'val1' }, name: 'test-value', settings: { 'key1' => 'val1' }, stack_id: 3.14 } }

  describe ':grafana_frontend_o11y_app' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_frontend_o11y_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_frontend_o11y_app', 'test')
        validate_required_attributes(config, [:allowed_origins, :extra_log_attributes, :name, :settings, :stack_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_frontend_o11y_app('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_frontend_o11y_app)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_frontend_o11y_app('test', required_attrs)

        expect(ref.id).to eq("${grafana_frontend_o11y_app.test.id}")
        expect(ref.collector_endpoint).to eq("${grafana_frontend_o11y_app.test.collector_endpoint}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_frontend_o11y_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_frontend_o11y_app', 'test')
        expect(config).not_to have_key('collector_endpoint')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_frontend_o11y_app('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_frontend_o11y_app', 'typed')
        expect(config['allowed_origins']).to be_a(Array)
        expect(config['extra_log_attributes']).to be_a(Hash)
        expect(config['name']).to be_a(String)
        expect(config['settings']).to be_a(Hash)
        expect(config['stack_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_frontend_o11y_app('first', required_attrs)
        synth.grafana_frontend_o11y_app('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_frontend_o11y_app')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_frontend_o11y_app,
    method: :grafana_frontend_o11y_app,
    required_attrs: { allowed_origins: ['test-value'], extra_log_attributes: { 'key1' => 'val1' }, name: 'test-value', settings: { 'key1' => 'val1' }, stack_id: 3.14 },
    expected_outputs: [:id, :collector_endpoint],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
