# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_route resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallRoute do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { escalation_chain_id: 'test-value', integration_id: 'test-value', position: 3.14, routing_regex: 'test-value' } }

  describe ':grafana_oncall_route' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'test')
        validate_required_attributes(config, [:escalation_chain_id, :integration_id, :position, :routing_regex])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_route('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_route)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_route('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_route.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ msteams: [{ 'key1' => 'val1' }], routing_type: 'test-value', slack: [{ 'key1' => 'val1' }], telegram: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_route', 'full')
        expect(config).to have_key('msteams')
        expect(config).to have_key('routing_type')
        expect(config).to have_key('slack')
        expect(config).to have_key('telegram')
      end
    end

    context 'optional attributes' do
      it 'includes msteams when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('opt', required_attrs.merge(msteams: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'opt')
        expect(config).to have_key('msteams')
      end

      it 'omits msteams when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'minimal')
        expect(config).not_to have_key('msteams')
      end
      it 'includes routing_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('opt', required_attrs.merge(routing_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'opt')
        expect(config).to have_key('routing_type')
      end

      it 'omits routing_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'minimal')
        expect(config).not_to have_key('routing_type')
      end
      it 'includes slack when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('opt', required_attrs.merge(slack: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'opt')
        expect(config).to have_key('slack')
      end

      it 'omits slack when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'minimal')
        expect(config).not_to have_key('slack')
      end
      it 'includes telegram when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('opt', required_attrs.merge(telegram: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'opt')
        expect(config).to have_key('telegram')
      end

      it 'omits telegram when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_route', 'minimal')
        expect(config).not_to have_key('telegram')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_route', 'typed')
        expect(config['escalation_chain_id']).to be_a(String)
        expect(config['integration_id']).to be_a(String)
        expect(config['position']).to be_a(Float)
        expect(config['routing_regex']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_route('first', required_attrs)
        synth.grafana_oncall_route('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_route')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_route,
    method: :grafana_oncall_route,
    required_attrs: { escalation_chain_id: 'test-value', integration_id: 'test-value', position: 3.14, routing_regex: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
