# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_data_source_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDataSourceConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':grafana_data_source_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_data_source_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_data_source_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_data_source_config('test', required_attrs)

        expect(ref.id).to eq("${grafana_data_source_config.test.id}")
        expect(ref.uid).to eq("${grafana_data_source_config.test.uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_data_source_config', 'test')
        expect(config).not_to have_key('uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ http_headers: { 'key1' => 'val1' }, json_data_encoded: 'test-value', org_id: 'test-value', secure_json_data_encoded: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_data_source_config', 'full')
        expect(config).to have_key('http_headers')
        expect(config).to have_key('json_data_encoded')
        expect(config).to have_key('org_id')
        expect(config).to have_key('secure_json_data_encoded')
      end
    end

    context 'optional attributes' do
      it 'includes http_headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('opt', required_attrs.merge(http_headers: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'opt')
        expect(config).to have_key('http_headers')
      end

      it 'omits http_headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'minimal')
        expect(config).not_to have_key('http_headers')
      end
      it 'includes json_data_encoded when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('opt', required_attrs.merge(json_data_encoded: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'opt')
        expect(config).to have_key('json_data_encoded')
      end

      it 'omits json_data_encoded when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'minimal')
        expect(config).not_to have_key('json_data_encoded')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes secure_json_data_encoded when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('opt', required_attrs.merge(secure_json_data_encoded: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'opt')
        expect(config).to have_key('secure_json_data_encoded')
      end

      it 'omits secure_json_data_encoded when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_data_source_config', 'minimal')
        expect(config).not_to have_key('secure_json_data_encoded')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:http_headers, :secure_json_data_encoded]
        expect(sensitive_fields).to include(:http_headers)
        expect(sensitive_fields).to include(:secure_json_data_encoded)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_data_source_config', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config('first', required_attrs)
        synth.grafana_data_source_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_data_source_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_data_source_config,
    method: :grafana_data_source_config,
    required_attrs: {},
    expected_outputs: [:id, :uid],
    sensitive_fields: [:http_headers, :secure_json_data_encoded],
    immutable_fields: [],
    boolean_fields: []
end
