# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_mute_timing resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaMuteTiming do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_mute_timing' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_mute_timing('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_mute_timing)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_mute_timing('test', required_attrs)

        expect(ref.id).to eq("${grafana_mute_timing.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disable_provenance: true, intervals: [{ 'key1' => 'val1' }], org_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_mute_timing', 'full')
        expect(config).to have_key('disable_provenance')
        expect(config).to have_key('intervals')
        expect(config).to have_key('org_id')
      end
    end

    context 'optional attributes' do
      it 'includes disable_provenance when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('opt', required_attrs.merge(disable_provenance: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'opt')
        expect(config).to have_key('disable_provenance')
      end

      it 'omits disable_provenance when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'minimal')
        expect(config).not_to have_key('disable_provenance')
      end
      it 'includes intervals when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('opt', required_attrs.merge(intervals: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'opt')
        expect(config).to have_key('intervals')
      end

      it 'omits intervals when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'minimal')
        expect(config).not_to have_key('intervals')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_mute_timing', 'minimal')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_provenance=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_provenance: val)
          synth.grafana_mute_timing("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_mute_timing', "bool_#{val}")
          expect(config['disable_provenance']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_mute_timing', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_mute_timing('first', required_attrs)
        synth.grafana_mute_timing('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_mute_timing')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_mute_timing,
    method: :grafana_mute_timing,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_provenance]
end
