# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_machine_learning_alert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaMachineLearningAlert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { title: 'test-value' } }

  describe ':grafana_machine_learning_alert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'test')
        validate_required_attributes(config, [:title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_alert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_machine_learning_alert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_alert('test', required_attrs)

        expect(ref.id).to eq("${grafana_machine_learning_alert.test.id}")
        expect(ref.for).to eq("${grafana_machine_learning_alert.test.for}")
        expect(ref.window).to eq("${grafana_machine_learning_alert.test.window}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'test')
        expect(config).not_to have_key('for')
        expect(config).not_to have_key('window')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations: { 'key1' => 'val1' }, anomaly_condition: 'test-value', job_id: 'test-value', labels: { 'key1' => 'val1' }, no_data_state: 'test-value', outlier_id: 'test-value', threshold: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'full')
        expect(config).to have_key('annotations')
        expect(config).to have_key('anomaly_condition')
        expect(config).to have_key('job_id')
        expect(config).to have_key('labels')
        expect(config).to have_key('no_data_state')
        expect(config).to have_key('outlier_id')
        expect(config).to have_key('threshold')
      end
    end

    context 'optional attributes' do
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes anomaly_condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(anomaly_condition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('anomaly_condition')
      end

      it 'omits anomaly_condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('anomaly_condition')
      end
      it 'includes job_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(job_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('job_id')
      end

      it 'omits job_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('job_id')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes no_data_state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(no_data_state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('no_data_state')
      end

      it 'omits no_data_state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('no_data_state')
      end
      it 'includes outlier_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(outlier_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('outlier_id')
      end

      it 'omits outlier_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('outlier_id')
      end
      it 'includes threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('opt', required_attrs.merge(threshold: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'opt')
        expect(config).to have_key('threshold')
      end

      it 'omits threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'minimal')
        expect(config).not_to have_key('threshold')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_alert', 'typed')
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_alert('first', required_attrs)
        synth.grafana_machine_learning_alert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_machine_learning_alert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_machine_learning_alert,
    method: :grafana_machine_learning_alert,
    required_attrs: { title: 'test-value' },
    expected_outputs: [:id, :for, :window],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
