# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_organization_preferences resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOrganizationPreferences do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':grafana_organization_preferences' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_organization_preferences('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_organization_preferences)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_organization_preferences('test', required_attrs)

        expect(ref.id).to eq("${grafana_organization_preferences.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ home_dashboard_uid: 'test-value', org_id: 'test-value', theme: 'test-value', timezone: 'test-value', week_start: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_organization_preferences', 'full')
        expect(config).to have_key('home_dashboard_uid')
        expect(config).to have_key('org_id')
        expect(config).to have_key('theme')
        expect(config).to have_key('timezone')
        expect(config).to have_key('week_start')
      end
    end

    context 'optional attributes' do
      it 'includes home_dashboard_uid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('opt', required_attrs.merge(home_dashboard_uid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'opt')
        expect(config).to have_key('home_dashboard_uid')
      end

      it 'omits home_dashboard_uid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'minimal')
        expect(config).not_to have_key('home_dashboard_uid')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes theme when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('opt', required_attrs.merge(theme: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'opt')
        expect(config).to have_key('theme')
      end

      it 'omits theme when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'minimal')
        expect(config).not_to have_key('theme')
      end
      it 'includes timezone when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('opt', required_attrs.merge(timezone: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'opt')
        expect(config).to have_key('timezone')
      end

      it 'omits timezone when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'minimal')
        expect(config).not_to have_key('timezone')
      end
      it 'includes week_start when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('opt', required_attrs.merge(week_start: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'opt')
        expect(config).to have_key('week_start')
      end

      it 'omits week_start when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization_preferences', 'minimal')
        expect(config).not_to have_key('week_start')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_organization_preferences', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization_preferences('first', required_attrs)
        synth.grafana_organization_preferences('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_organization_preferences')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_organization_preferences,
    method: :grafana_organization_preferences,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
