# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_k6_project_limits resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaK6ProjectLimits do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project_id: 'test-value' } }

  describe ':grafana_k6_project_limits' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'test')
        validate_required_attributes(config, [:project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_k6_project_limits('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_k6_project_limits)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_k6_project_limits('test', required_attrs)

        expect(ref.id).to eq("${grafana_k6_project_limits.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ duration_max_per_test: 3.14, vu_browser_max_per_test: 3.14, vu_max_per_test: 3.14, vuh_max_per_month: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'full')
        expect(config).to have_key('duration_max_per_test')
        expect(config).to have_key('vu_browser_max_per_test')
        expect(config).to have_key('vu_max_per_test')
        expect(config).to have_key('vuh_max_per_month')
      end
    end

    context 'optional attributes' do
      it 'includes duration_max_per_test when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('opt', required_attrs.merge(duration_max_per_test: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'opt')
        expect(config).to have_key('duration_max_per_test')
      end

      it 'omits duration_max_per_test when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'minimal')
        expect(config).not_to have_key('duration_max_per_test')
      end
      it 'includes vu_browser_max_per_test when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('opt', required_attrs.merge(vu_browser_max_per_test: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'opt')
        expect(config).to have_key('vu_browser_max_per_test')
      end

      it 'omits vu_browser_max_per_test when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'minimal')
        expect(config).not_to have_key('vu_browser_max_per_test')
      end
      it 'includes vu_max_per_test when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('opt', required_attrs.merge(vu_max_per_test: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'opt')
        expect(config).to have_key('vu_max_per_test')
      end

      it 'omits vu_max_per_test when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'minimal')
        expect(config).not_to have_key('vu_max_per_test')
      end
      it 'includes vuh_max_per_month when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('opt', required_attrs.merge(vuh_max_per_month: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'opt')
        expect(config).to have_key('vuh_max_per_month')
      end

      it 'omits vuh_max_per_month when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'minimal')
        expect(config).not_to have_key('vuh_max_per_month')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_k6_project_limits', 'typed')
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_k6_project_limits('first', required_attrs)
        synth.grafana_k6_project_limits('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_k6_project_limits')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_k6_project_limits,
    method: :grafana_k6_project_limits,
    required_attrs: { project_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
