# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_organization resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOrganization do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_organization' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_organization', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_organization('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_organization)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_organization('test', required_attrs)

        expect(ref.id).to eq("${grafana_organization.test.id}")
        expect(ref.org_id).to eq("${grafana_organization.test.org_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_organization', 'test')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ admin_user: 'test-value', admins: ['test-value'], create_users: true, editors: ['test-value'], users_without_access: ['test-value'], viewers: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_organization', 'full')
        expect(config).to have_key('admin_user')
        expect(config).to have_key('admins')
        expect(config).to have_key('create_users')
        expect(config).to have_key('editors')
        expect(config).to have_key('users_without_access')
        expect(config).to have_key('viewers')
      end
    end

    context 'optional attributes' do
      it 'includes admin_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(admin_user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('admin_user')
      end

      it 'omits admin_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('admin_user')
      end
      it 'includes admins when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(admins: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('admins')
      end

      it 'omits admins when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('admins')
      end
      it 'includes create_users when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(create_users: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('create_users')
      end

      it 'omits create_users when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('create_users')
      end
      it 'includes editors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(editors: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('editors')
      end

      it 'omits editors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('editors')
      end
      it 'includes users_without_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(users_without_access: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('users_without_access')
      end

      it 'omits users_without_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('users_without_access')
      end
      it 'includes viewers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('opt', required_attrs.merge(viewers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'opt')
        expect(config).to have_key('viewers')
      end

      it 'omits viewers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_organization', 'minimal')
        expect(config).not_to have_key('viewers')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts create_users=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(create_users: val)
          synth.grafana_organization("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_organization', "bool_#{val}")
          expect(config['create_users']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_organization', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_organization('first', required_attrs)
        synth.grafana_organization('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_organization')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_organization,
    method: :grafana_organization,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :org_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:create_users]
end
