# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_report resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaReport do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', recipients: ['test-value'], schedule: [{ 'key1' => 'val1' }] } }

  describe ':grafana_report' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_report', 'test')
        validate_required_attributes(config, [:name, :recipients, :schedule])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_report('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_report)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_report('test', required_attrs)

        expect(ref.id).to eq("${grafana_report.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dashboards: [{ 'key1' => 'val1' }], formats: ['test-value'], include_dashboard_link: true, include_table_csv: true, layout: 'test-value', message: 'test-value', org_id: 'test-value', orientation: 'test-value', reply_to: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_report', 'full')
        expect(config).to have_key('dashboards')
        expect(config).to have_key('formats')
        expect(config).to have_key('include_dashboard_link')
        expect(config).to have_key('include_table_csv')
        expect(config).to have_key('layout')
        expect(config).to have_key('message')
        expect(config).to have_key('org_id')
        expect(config).to have_key('orientation')
        expect(config).to have_key('reply_to')
      end
    end

    context 'optional attributes' do
      it 'includes dashboards when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(dashboards: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('dashboards')
      end

      it 'omits dashboards when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('dashboards')
      end
      it 'includes formats when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(formats: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('formats')
      end

      it 'omits formats when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('formats')
      end
      it 'includes include_dashboard_link when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(include_dashboard_link: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('include_dashboard_link')
      end

      it 'omits include_dashboard_link when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('include_dashboard_link')
      end
      it 'includes include_table_csv when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(include_table_csv: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('include_table_csv')
      end

      it 'omits include_table_csv when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('include_table_csv')
      end
      it 'includes layout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(layout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('layout')
      end

      it 'omits layout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('layout')
      end
      it 'includes message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(message: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('message')
      end

      it 'omits message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('message')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes orientation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(orientation: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('orientation')
      end

      it 'omits orientation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('orientation')
      end
      it 'includes reply_to when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('opt', required_attrs.merge(reply_to: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'opt')
        expect(config).to have_key('reply_to')
      end

      it 'omits reply_to when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_report', 'minimal')
        expect(config).not_to have_key('reply_to')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts include_dashboard_link=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(include_dashboard_link: val)
          synth.grafana_report("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_report', "bool_#{val}")
          expect(config['include_dashboard_link']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts include_table_csv=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(include_table_csv: val)
          synth.grafana_report("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_report', "bool_#{val}")
          expect(config['include_table_csv']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_report', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['recipients']).to be_a(Array)
        expect(config['schedule']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_report('first', required_attrs)
        synth.grafana_report('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_report')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_report,
    method: :grafana_report,
    required_attrs: { name: 'test-value', recipients: ['test-value'], schedule: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:include_dashboard_link, :include_table_csv]
end
