# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_provider_azure_credential resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudProviderAzureCredential do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { client_id: 'test-value', client_secret: 'test-value', name: 'test-value', stack_id: 'test-value', tenant_id: 'test-value' } }

  describe ':grafana_cloud_provider_azure_credential' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'test')
        validate_required_attributes(config, [:client_id, :client_secret, :name, :stack_id, :tenant_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_azure_credential('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_provider_azure_credential)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_azure_credential('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_provider_azure_credential.test.id}")
        expect(ref.resource_id).to eq("${grafana_cloud_provider_azure_credential.test.resource_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'test')
        expect(config).not_to have_key('resource_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_discovery_configuration: [{ 'key1' => 'val1' }], resource_discovery_tag_filter: [{ 'key1' => 'val1' }], resource_tags_to_add_to_metrics: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'full')
        expect(config).to have_key('auto_discovery_configuration')
        expect(config).to have_key('resource_discovery_tag_filter')
        expect(config).to have_key('resource_tags_to_add_to_metrics')
      end
    end

    context 'optional attributes' do
      it 'includes auto_discovery_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('opt', required_attrs.merge(auto_discovery_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'opt')
        expect(config).to have_key('auto_discovery_configuration')
      end

      it 'omits auto_discovery_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'minimal')
        expect(config).not_to have_key('auto_discovery_configuration')
      end
      it 'includes resource_discovery_tag_filter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('opt', required_attrs.merge(resource_discovery_tag_filter: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'opt')
        expect(config).to have_key('resource_discovery_tag_filter')
      end

      it 'omits resource_discovery_tag_filter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'minimal')
        expect(config).not_to have_key('resource_discovery_tag_filter')
      end
      it 'includes resource_tags_to_add_to_metrics when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('opt', required_attrs.merge(resource_tags_to_add_to_metrics: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'opt')
        expect(config).to have_key('resource_tags_to_add_to_metrics')
      end

      it 'omits resource_tags_to_add_to_metrics when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'minimal')
        expect(config).not_to have_key('resource_tags_to_add_to_metrics')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:client_secret]
        expect(sensitive_fields).to include(:client_secret)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_azure_credential', 'typed')
        expect(config['client_id']).to be_a(String)
        expect(config['client_secret']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['stack_id']).to be_a(String)
        expect(config['tenant_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_azure_credential('first', required_attrs)
        synth.grafana_cloud_provider_azure_credential('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_provider_azure_credential')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_provider_azure_credential,
    method: :grafana_cloud_provider_azure_credential,
    required_attrs: { client_id: 'test-value', client_secret: 'test-value', name: 'test-value', stack_id: 'test-value', tenant_id: 'test-value' },
    expected_outputs: [:id, :resource_id],
    sensitive_fields: [:client_secret],
    immutable_fields: [],
    boolean_fields: []
end
