# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_scim_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaScimConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { allow_non_provisioned_users: true, enable_group_sync: true, enable_user_sync: true } }

  describe ':grafana_scim_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_scim_config', 'test')
        validate_required_attributes(config, [:allow_non_provisioned_users, :enable_group_sync, :enable_user_sync])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_scim_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_scim_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_scim_config('test', required_attrs)

        expect(ref.id).to eq("${grafana_scim_config.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ org_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_scim_config', 'full')
        expect(config).to have_key('org_id')
      end
    end

    context 'optional attributes' do
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_scim_config', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_scim_config', 'minimal')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_non_provisioned_users=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_non_provisioned_users: val)
          synth.grafana_scim_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_scim_config', "bool_#{val}")
          expect(config['allow_non_provisioned_users']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_group_sync=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_group_sync: val)
          synth.grafana_scim_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_scim_config', "bool_#{val}")
          expect(config['enable_group_sync']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_user_sync=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_user_sync: val)
          synth.grafana_scim_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_scim_config', "bool_#{val}")
          expect(config['enable_user_sync']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_scim_config', 'typed')
        expect([true, false]).to include(config['allow_non_provisioned_users'])
        expect([true, false]).to include(config['enable_group_sync'])
        expect([true, false]).to include(config['enable_user_sync'])
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_scim_config('first', required_attrs)
        synth.grafana_scim_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_scim_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_scim_config,
    method: :grafana_scim_config,
    required_attrs: { allow_non_provisioned_users: true, enable_group_sync: true, enable_user_sync: true },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_non_provisioned_users, :enable_group_sync, :enable_user_sync]
end
