# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_dashboard_public resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDashboardPublic do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { dashboard_uid: 'test-value' } }

  describe ':grafana_dashboard_public' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'test')
        validate_required_attributes(config, [:dashboard_uid])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_public('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_dashboard_public)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_public('test', required_attrs)

        expect(ref.id).to eq("${grafana_dashboard_public.test.id}")
        expect(ref.access_token).to eq("${grafana_dashboard_public.test.access_token}")
        expect(ref.uid).to eq("${grafana_dashboard_public.test.uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_public', 'test')
        expect(config).not_to have_key('access_token')
        expect(config).not_to have_key('uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations_enabled: true, is_enabled: true, org_id: 'test-value', share: 'test-value', time_selection_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_public', 'full')
        expect(config).to have_key('annotations_enabled')
        expect(config).to have_key('is_enabled')
        expect(config).to have_key('org_id')
        expect(config).to have_key('share')
        expect(config).to have_key('time_selection_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes annotations_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('opt', required_attrs.merge(annotations_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'opt')
        expect(config).to have_key('annotations_enabled')
      end

      it 'omits annotations_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'minimal')
        expect(config).not_to have_key('annotations_enabled')
      end
      it 'includes is_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('opt', required_attrs.merge(is_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'opt')
        expect(config).to have_key('is_enabled')
      end

      it 'omits is_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'minimal')
        expect(config).not_to have_key('is_enabled')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes share when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('opt', required_attrs.merge(share: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'opt')
        expect(config).to have_key('share')
      end

      it 'omits share when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'minimal')
        expect(config).not_to have_key('share')
      end
      it 'includes time_selection_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('opt', required_attrs.merge(time_selection_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'opt')
        expect(config).to have_key('time_selection_enabled')
      end

      it 'omits time_selection_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_public', 'minimal')
        expect(config).not_to have_key('time_selection_enabled')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts annotations_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(annotations_enabled: val)
          synth.grafana_dashboard_public("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_dashboard_public', "bool_#{val}")
          expect(config['annotations_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_enabled: val)
          synth.grafana_dashboard_public("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_dashboard_public', "bool_#{val}")
          expect(config['is_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts time_selection_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(time_selection_enabled: val)
          synth.grafana_dashboard_public("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_dashboard_public', "bool_#{val}")
          expect(config['time_selection_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_public', 'typed')
        expect(config['dashboard_uid']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_public('first', required_attrs)
        synth.grafana_dashboard_public('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_dashboard_public')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_dashboard_public,
    method: :grafana_dashboard_public,
    required_attrs: { dashboard_uid: 'test-value' },
    expected_outputs: [:id, :access_token, :uid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:annotations_enabled, :is_enabled, :time_selection_enabled]
end
