# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_user_notification_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallUserNotificationRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { type: 'test-value', user_id: 'test-value' } }

  describe ':grafana_oncall_user_notification_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'test')
        validate_required_attributes(config, [:type, :user_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_user_notification_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_user_notification_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_user_notification_rule('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_user_notification_rule.test.id}")
        expect(ref.important).to eq("${grafana_oncall_user_notification_rule.test.important}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'test')
        expect(config).not_to have_key('important')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ duration: 3.14, position: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'full')
        expect(config).to have_key('duration')
        expect(config).to have_key('position')
      end
    end

    context 'optional attributes' do
      it 'includes duration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('opt', required_attrs.merge(duration: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'opt')
        expect(config).to have_key('duration')
      end

      it 'omits duration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'minimal')
        expect(config).not_to have_key('duration')
      end
      it 'includes position when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('opt', required_attrs.merge(position: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'opt')
        expect(config).to have_key('position')
      end

      it 'omits position when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'minimal')
        expect(config).not_to have_key('position')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_user_notification_rule', 'typed')
        expect(config['type']).to be_a(String)
        expect(config['user_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_user_notification_rule('first', required_attrs)
        synth.grafana_oncall_user_notification_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_user_notification_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_user_notification_rule,
    method: :grafana_oncall_user_notification_rule,
    required_attrs: { type: 'test-value', user_id: 'test-value' },
    expected_outputs: [:id, :important],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
