# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_synthetic_monitoring_installation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaSyntheticMonitoringInstallation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metrics_publisher_key: 'test-value', stack_id: 'test-value' } }

  describe ':grafana_synthetic_monitoring_installation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_installation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_installation', 'test')
        validate_required_attributes(config, [:metrics_publisher_key, :stack_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_installation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_synthetic_monitoring_installation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_installation('test', required_attrs)

        expect(ref.id).to eq("${grafana_synthetic_monitoring_installation.test.id}")
        expect(ref.sm_access_token).to eq("${grafana_synthetic_monitoring_installation.test.sm_access_token}")
        expect(ref.stack_sm_api_url).to eq("${grafana_synthetic_monitoring_installation.test.stack_sm_api_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_installation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_installation', 'test')
        expect(config).not_to have_key('sm_access_token')
        expect(config).not_to have_key('stack_sm_api_url')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:metrics_publisher_key]
        expect(sensitive_fields).to include(:metrics_publisher_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_installation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_installation', 'typed')
        expect(config['metrics_publisher_key']).to be_a(String)
        expect(config['stack_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_installation('first', required_attrs)
        synth.grafana_synthetic_monitoring_installation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_synthetic_monitoring_installation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_synthetic_monitoring_installation,
    method: :grafana_synthetic_monitoring_installation,
    required_attrs: { metrics_publisher_key: 'test-value', stack_id: 'test-value' },
    expected_outputs: [:id, :sm_access_token, :stack_sm_api_url],
    sensitive_fields: [:metrics_publisher_key],
    immutable_fields: [],
    boolean_fields: []
end
