# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_data_source_config_lbac_rules resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDataSourceConfigLbacRules do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { datasource_uid: 'test-value', rules: 'test-value' } }

  describe ':grafana_data_source_config_lbac_rules' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config_lbac_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_data_source_config_lbac_rules', 'test')
        validate_required_attributes(config, [:datasource_uid, :rules])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_data_source_config_lbac_rules('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_data_source_config_lbac_rules)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_data_source_config_lbac_rules('test', required_attrs)

        expect(ref.id).to eq("${grafana_data_source_config_lbac_rules.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config_lbac_rules('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_data_source_config_lbac_rules', 'typed')
        expect(config['datasource_uid']).to be_a(String)
        expect(config['rules']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_data_source_config_lbac_rules('first', required_attrs)
        synth.grafana_data_source_config_lbac_rules('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_data_source_config_lbac_rules')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_data_source_config_lbac_rules,
    method: :grafana_data_source_config_lbac_rules,
    required_attrs: { datasource_uid: 'test-value', rules: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
