# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_team resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaTeam do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_team' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_team', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_team('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_team)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_team('test', required_attrs)

        expect(ref.id).to eq("${grafana_team.test.id}")
        expect(ref.team_id).to eq("${grafana_team.test.team_id}")
        expect(ref.team_uid).to eq("${grafana_team.test.team_uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_team', 'test')
        expect(config).not_to have_key('team_id')
        expect(config).not_to have_key('team_uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ email: 'test-value', ignore_externally_synced_members: true, members: ['test-value'], org_id: 'test-value', preferences: [{ 'key1' => 'val1' }], team_sync: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_team', 'full')
        expect(config).to have_key('email')
        expect(config).to have_key('ignore_externally_synced_members')
        expect(config).to have_key('members')
        expect(config).to have_key('org_id')
        expect(config).to have_key('preferences')
        expect(config).to have_key('team_sync')
      end
    end

    context 'optional attributes' do
      it 'includes email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('email')
      end

      it 'omits email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('email')
      end
      it 'includes ignore_externally_synced_members when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(ignore_externally_synced_members: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('ignore_externally_synced_members')
      end

      it 'omits ignore_externally_synced_members when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('ignore_externally_synced_members')
      end
      it 'includes members when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(members: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('members')
      end

      it 'omits members when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('members')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes preferences when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(preferences: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('preferences')
      end

      it 'omits preferences when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('preferences')
      end
      it 'includes team_sync when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('opt', required_attrs.merge(team_sync: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'opt')
        expect(config).to have_key('team_sync')
      end

      it 'omits team_sync when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_team', 'minimal')
        expect(config).not_to have_key('team_sync')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ignore_externally_synced_members=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_externally_synced_members: val)
          synth.grafana_team("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_team', "bool_#{val}")
          expect(config['ignore_externally_synced_members']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_team', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_team('first', required_attrs)
        synth.grafana_team('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_team')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_team,
    method: :grafana_team,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :team_id, :team_uid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ignore_externally_synced_members]
end
