# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { email: 'test-value', password: 'test-value' } }

  describe ':grafana_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_user', 'test')
        validate_required_attributes(config, [:email, :password])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_user('test', required_attrs)

        expect(ref.id).to eq("${grafana_user.test.id}")
        expect(ref.user_id).to eq("${grafana_user.test.user_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_user', 'test')
        expect(config).not_to have_key('user_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ is_admin: true, login: 'test-value', name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_user', 'full')
        expect(config).to have_key('is_admin')
        expect(config).to have_key('login')
        expect(config).to have_key('name')
      end
    end

    context 'optional attributes' do
      it 'includes is_admin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('opt', required_attrs.merge(is_admin: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'opt')
        expect(config).to have_key('is_admin')
      end

      it 'omits is_admin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'minimal')
        expect(config).not_to have_key('is_admin')
      end
      it 'includes login when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('opt', required_attrs.merge(login: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'opt')
        expect(config).to have_key('login')
      end

      it 'omits login when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'minimal')
        expect(config).not_to have_key('login')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_user', 'minimal')
        expect(config).not_to have_key('name')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts is_admin=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_admin: val)
          synth.grafana_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_user', "bool_#{val}")
          expect(config['is_admin']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_user', 'typed')
        expect(config['email']).to be_a(String)
        expect(config['password']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_user('first', required_attrs)
        synth.grafana_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_user,
    method: :grafana_user,
    required_attrs: { email: 'test-value', password: 'test-value' },
    expected_outputs: [:id, :user_id],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:is_admin]
end
