# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_role_assignment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaRoleAssignment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_uid: 'test-value' } }

  describe ':grafana_role_assignment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'test')
        validate_required_attributes(config, [:role_uid])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_role_assignment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_role_assignment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_role_assignment('test', required_attrs)

        expect(ref.id).to eq("${grafana_role_assignment.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ org_id: 'test-value', service_accounts: ['test-value'], teams: ['test-value'], users: [3.14] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_role_assignment', 'full')
        expect(config).to have_key('org_id')
        expect(config).to have_key('service_accounts')
        expect(config).to have_key('teams')
        expect(config).to have_key('users')
      end
    end

    context 'optional attributes' do
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes service_accounts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('opt', required_attrs.merge(service_accounts: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'opt')
        expect(config).to have_key('service_accounts')
      end

      it 'omits service_accounts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'minimal')
        expect(config).not_to have_key('service_accounts')
      end
      it 'includes teams when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('opt', required_attrs.merge(teams: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'opt')
        expect(config).to have_key('teams')
      end

      it 'omits teams when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'minimal')
        expect(config).not_to have_key('teams')
      end
      it 'includes users when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('opt', required_attrs.merge(users: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'opt')
        expect(config).to have_key('users')
      end

      it 'omits users when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_role_assignment', 'minimal')
        expect(config).not_to have_key('users')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_role_assignment', 'typed')
        expect(config['role_uid']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_role_assignment('first', required_attrs)
        synth.grafana_role_assignment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_role_assignment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_role_assignment,
    method: :grafana_role_assignment,
    required_attrs: { role_uid: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
