# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_schedule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallSchedule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', type: 'test-value' } }

  describe ':grafana_oncall_schedule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'test')
        validate_required_attributes(config, [:name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_schedule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_schedule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_schedule('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_schedule.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enable_web_overrides: true, ical_url_overrides: 'test-value', ical_url_primary: 'test-value', shifts: ['test-value'], slack: [{ 'key1' => 'val1' }], team_id: 'test-value', time_zone: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'full')
        expect(config).to have_key('enable_web_overrides')
        expect(config).to have_key('ical_url_overrides')
        expect(config).to have_key('ical_url_primary')
        expect(config).to have_key('shifts')
        expect(config).to have_key('slack')
        expect(config).to have_key('team_id')
        expect(config).to have_key('time_zone')
      end
    end

    context 'optional attributes' do
      it 'includes enable_web_overrides when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(enable_web_overrides: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('enable_web_overrides')
      end

      it 'omits enable_web_overrides when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('enable_web_overrides')
      end
      it 'includes ical_url_overrides when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(ical_url_overrides: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('ical_url_overrides')
      end

      it 'omits ical_url_overrides when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('ical_url_overrides')
      end
      it 'includes ical_url_primary when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(ical_url_primary: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('ical_url_primary')
      end

      it 'omits ical_url_primary when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('ical_url_primary')
      end
      it 'includes shifts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(shifts: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('shifts')
      end

      it 'omits shifts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('shifts')
      end
      it 'includes slack when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(slack: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('slack')
      end

      it 'omits slack when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('slack')
      end
      it 'includes team_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(team_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('team_id')
      end

      it 'omits team_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('team_id')
      end
      it 'includes time_zone when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('opt', required_attrs.merge(time_zone: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'opt')
        expect(config).to have_key('time_zone')
      end

      it 'omits time_zone when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'minimal')
        expect(config).not_to have_key('time_zone')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_web_overrides=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_web_overrides: val)
          synth.grafana_oncall_schedule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_oncall_schedule', "bool_#{val}")
          expect(config['enable_web_overrides']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_schedule', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_schedule('first', required_attrs)
        synth.grafana_oncall_schedule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_schedule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_schedule,
    method: :grafana_oncall_schedule,
    required_attrs: { name: 'test-value', type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_web_overrides]
end
