# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_dashboard_permission_item resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDashboardPermissionItem do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { dashboard_uid: 'test-value', permission: 'test-value' } }

  describe ':grafana_dashboard_permission_item' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'test')
        validate_required_attributes(config, [:dashboard_uid, :permission])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_permission_item('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_dashboard_permission_item)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_permission_item('test', required_attrs)

        expect(ref.id).to eq("${grafana_dashboard_permission_item.test.id}")
        expect(ref.org_id).to eq("${grafana_dashboard_permission_item.test.org_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'test')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ role: 'test-value', team: 'test-value', user: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'full')
        expect(config).to have_key('role')
        expect(config).to have_key('team')
        expect(config).to have_key('user')
      end
    end

    context 'optional attributes' do
      it 'includes role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('opt', required_attrs.merge(role: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'opt')
        expect(config).to have_key('role')
      end

      it 'omits role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'minimal')
        expect(config).not_to have_key('role')
      end
      it 'includes team when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('opt', required_attrs.merge(team: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'opt')
        expect(config).to have_key('team')
      end

      it 'omits team when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'minimal')
        expect(config).not_to have_key('team')
      end
      it 'includes user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('opt', required_attrs.merge(user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'opt')
        expect(config).to have_key('user')
      end

      it 'omits user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'minimal')
        expect(config).not_to have_key('user')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission_item', 'typed')
        expect(config['dashboard_uid']).to be_a(String)
        expect(config['permission']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission_item('first', required_attrs)
        synth.grafana_dashboard_permission_item('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_dashboard_permission_item')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_dashboard_permission_item,
    method: :grafana_dashboard_permission_item,
    required_attrs: { dashboard_uid: 'test-value', permission: 'test-value' },
    expected_outputs: [:id, :org_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
