# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_library_panel resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaLibraryPanel do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { model_json: 'test-value', name: 'test-value' } }

  describe ':grafana_library_panel' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_library_panel', 'test')
        validate_required_attributes(config, [:model_json, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_library_panel('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_library_panel)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_library_panel('test', required_attrs)

        expect(ref.id).to eq("${grafana_library_panel.test.id}")
        expect(ref.created).to eq("${grafana_library_panel.test.created}")
        expect(ref.dashboard_ids).to eq("${grafana_library_panel.test.dashboard_ids}")
        expect(ref.description).to eq("${grafana_library_panel.test.description}")
        expect(ref.folder_name).to eq("${grafana_library_panel.test.folder_name}")
        expect(ref.panel_id).to eq("${grafana_library_panel.test.panel_id}")
        expect(ref.type).to eq("${grafana_library_panel.test.type}")
        expect(ref.uid).to eq("${grafana_library_panel.test.uid}")
        expect(ref.updated).to eq("${grafana_library_panel.test.updated}")
        expect(ref.version).to eq("${grafana_library_panel.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_library_panel', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('dashboard_ids')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('folder_name')
        expect(config).not_to have_key('panel_id')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('updated')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ folder_uid: 'test-value', org_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_library_panel', 'full')
        expect(config).to have_key('folder_uid')
        expect(config).to have_key('org_id')
      end
    end

    context 'optional attributes' do
      it 'includes folder_uid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('opt', required_attrs.merge(folder_uid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_library_panel', 'opt')
        expect(config).to have_key('folder_uid')
      end

      it 'omits folder_uid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_library_panel', 'minimal')
        expect(config).not_to have_key('folder_uid')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_library_panel', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_library_panel', 'minimal')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_library_panel', 'typed')
        expect(config['model_json']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_library_panel('first', required_attrs)
        synth.grafana_library_panel('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_library_panel')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_library_panel,
    method: :grafana_library_panel,
    required_attrs: { model_json: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created, :dashboard_ids, :description, :folder_name, :panel_id, :type, :uid, :updated, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
