# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_access_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudAccessPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', realm: [{ 'key1' => 'val1' }], region: 'test-value', scopes: ['test-value'] } }

  describe ':grafana_cloud_access_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'test')
        validate_required_attributes(config, [:name, :realm, :region, :scopes])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_access_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_access_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_access_policy('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_access_policy.test.id}")
        expect(ref.created_at).to eq("${grafana_cloud_access_policy.test.created_at}")
        expect(ref.policy_id).to eq("${grafana_cloud_access_policy.test.policy_id}")
        expect(ref.updated_at).to eq("${grafana_cloud_access_policy.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('policy_id')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ conditions: [{ 'key1' => 'val1' }], display_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'full')
        expect(config).to have_key('conditions')
        expect(config).to have_key('display_name')
      end
    end

    context 'optional attributes' do
      it 'includes conditions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('opt', required_attrs.merge(conditions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'opt')
        expect(config).to have_key('conditions')
      end

      it 'omits conditions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'minimal')
        expect(config).not_to have_key('conditions')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'minimal')
        expect(config).not_to have_key('display_name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_access_policy', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['realm']).to be_a(Array)
        expect(config['region']).to be_a(String)
        expect(config['scopes']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_access_policy('first', required_attrs)
        synth.grafana_cloud_access_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_access_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_access_policy,
    method: :grafana_cloud_access_policy,
    required_attrs: { name: 'test-value', realm: [{ 'key1' => 'val1' }], region: 'test-value', scopes: ['test-value'] },
    expected_outputs: [:id, :created_at, :policy_id, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
