# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_dashboard resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDashboard do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { config_json: 'test-value' } }

  describe ':grafana_dashboard' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_dashboard', 'test')
        validate_required_attributes(config, [:config_json])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_dashboard)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard('test', required_attrs)

        expect(ref.id).to eq("${grafana_dashboard.test.id}")
        expect(ref.dashboard_id).to eq("${grafana_dashboard.test.dashboard_id}")
        expect(ref.uid).to eq("${grafana_dashboard.test.uid}")
        expect(ref.url).to eq("${grafana_dashboard.test.url}")
        expect(ref.version).to eq("${grafana_dashboard.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard', 'test')
        expect(config).not_to have_key('dashboard_id')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('url')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ folder: 'test-value', message: 'test-value', org_id: 'test-value', overwrite: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard', 'full')
        expect(config).to have_key('folder')
        expect(config).to have_key('message')
        expect(config).to have_key('org_id')
        expect(config).to have_key('overwrite')
      end
    end

    context 'optional attributes' do
      it 'includes folder when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('opt', required_attrs.merge(folder: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'opt')
        expect(config).to have_key('folder')
      end

      it 'omits folder when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'minimal')
        expect(config).not_to have_key('folder')
      end
      it 'includes message when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('opt', required_attrs.merge(message: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'opt')
        expect(config).to have_key('message')
      end

      it 'omits message when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'minimal')
        expect(config).not_to have_key('message')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes overwrite when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('opt', required_attrs.merge(overwrite: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'opt')
        expect(config).to have_key('overwrite')
      end

      it 'omits overwrite when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard', 'minimal')
        expect(config).not_to have_key('overwrite')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts overwrite=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(overwrite: val)
          synth.grafana_dashboard("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_dashboard', "bool_#{val}")
          expect(config['overwrite']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard', 'typed')
        expect(config['config_json']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard('first', required_attrs)
        synth.grafana_dashboard('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_dashboard')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_dashboard,
    method: :grafana_dashboard,
    required_attrs: { config_json: 'test-value' },
    expected_outputs: [:id, :dashboard_id, :uid, :url, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:overwrite]
end
