# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_synthetic_monitoring_probe resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaSyntheticMonitoringProbe do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { latitude: 3.14, longitude: 3.14, name: 'test-value', region: 'test-value' } }

  describe ':grafana_synthetic_monitoring_probe' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'test')
        validate_required_attributes(config, [:latitude, :longitude, :name, :region])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_probe('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_synthetic_monitoring_probe)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_probe('test', required_attrs)

        expect(ref.id).to eq("${grafana_synthetic_monitoring_probe.test.id}")
        expect(ref.auth_token).to eq("${grafana_synthetic_monitoring_probe.test.auth_token}")
        expect(ref.tenant_id).to eq("${grafana_synthetic_monitoring_probe.test.tenant_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'test')
        expect(config).not_to have_key('auth_token')
        expect(config).not_to have_key('tenant_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disable_browser_checks: true, disable_scripted_checks: true, labels: { 'key1' => 'val1' }, public: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'full')
        expect(config).to have_key('disable_browser_checks')
        expect(config).to have_key('disable_scripted_checks')
        expect(config).to have_key('labels')
        expect(config).to have_key('public')
      end
    end

    context 'optional attributes' do
      it 'includes disable_browser_checks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('opt', required_attrs.merge(disable_browser_checks: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'opt')
        expect(config).to have_key('disable_browser_checks')
      end

      it 'omits disable_browser_checks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'minimal')
        expect(config).not_to have_key('disable_browser_checks')
      end
      it 'includes disable_scripted_checks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('opt', required_attrs.merge(disable_scripted_checks: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'opt')
        expect(config).to have_key('disable_scripted_checks')
      end

      it 'omits disable_scripted_checks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'minimal')
        expect(config).not_to have_key('disable_scripted_checks')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes public when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('opt', required_attrs.merge(public: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'opt')
        expect(config).to have_key('public')
      end

      it 'omits public when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'minimal')
        expect(config).not_to have_key('public')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:auth_token]
        expect(sensitive_fields).to include(:auth_token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_browser_checks=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_browser_checks: val)
          synth.grafana_synthetic_monitoring_probe("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', "bool_#{val}")
          expect(config['disable_browser_checks']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_scripted_checks=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_scripted_checks: val)
          synth.grafana_synthetic_monitoring_probe("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', "bool_#{val}")
          expect(config['disable_scripted_checks']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts public=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(public: val)
          synth.grafana_synthetic_monitoring_probe("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', "bool_#{val}")
          expect(config['public']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_probe', 'typed')
        expect(config['latitude']).to be_a(Float)
        expect(config['longitude']).to be_a(Float)
        expect(config['name']).to be_a(String)
        expect(config['region']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_probe('first', required_attrs)
        synth.grafana_synthetic_monitoring_probe('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_synthetic_monitoring_probe')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_synthetic_monitoring_probe,
    method: :grafana_synthetic_monitoring_probe,
    required_attrs: { latitude: 3.14, longitude: 3.14, name: 'test-value', region: 'test-value' },
    expected_outputs: [:id, :auth_token, :tenant_id],
    sensitive_fields: [:auth_token],
    immutable_fields: [],
    boolean_fields: [:disable_browser_checks, :disable_scripted_checks, :public]
end
