# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_dashboard_permission resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaDashboardPermission do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':grafana_dashboard_permission' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_permission('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_dashboard_permission)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_dashboard_permission('test', required_attrs)

        expect(ref.id).to eq("${grafana_dashboard_permission.test.id}")
        expect(ref.dashboard_uid).to eq("${grafana_dashboard_permission.test.dashboard_uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'test')
        expect(config).not_to have_key('dashboard_uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ org_id: 'test-value', permissions: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'full')
        expect(config).to have_key('org_id')
        expect(config).to have_key('permissions')
      end
    end

    context 'optional attributes' do
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes permissions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('opt', required_attrs.merge(permissions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'opt')
        expect(config).to have_key('permissions')
      end

      it 'omits permissions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'minimal')
        expect(config).not_to have_key('permissions')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_dashboard_permission', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_dashboard_permission('first', required_attrs)
        synth.grafana_dashboard_permission('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_dashboard_permission')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_dashboard_permission,
    method: :grafana_dashboard_permission,
    required_attrs: {},
    expected_outputs: [:id, :dashboard_uid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
