# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_rule_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaRuleGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { folder_uid: 'test-value', interval_seconds: 3.14, name: 'test-value', rule: [{ 'key1' => 'val1' }] } }

  describe ':grafana_rule_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_rule_group', 'test')
        validate_required_attributes(config, [:folder_uid, :interval_seconds, :name, :rule])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_rule_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_rule_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_rule_group('test', required_attrs)

        expect(ref.id).to eq("${grafana_rule_group.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disable_provenance: true, org_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_rule_group', 'full')
        expect(config).to have_key('disable_provenance')
        expect(config).to have_key('org_id')
      end
    end

    context 'optional attributes' do
      it 'includes disable_provenance when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('opt', required_attrs.merge(disable_provenance: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_rule_group', 'opt')
        expect(config).to have_key('disable_provenance')
      end

      it 'omits disable_provenance when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_rule_group', 'minimal')
        expect(config).not_to have_key('disable_provenance')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_rule_group', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_rule_group', 'minimal')
        expect(config).not_to have_key('org_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_provenance=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_provenance: val)
          synth.grafana_rule_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_rule_group', "bool_#{val}")
          expect(config['disable_provenance']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_rule_group', 'typed')
        expect(config['folder_uid']).to be_a(String)
        expect(config['interval_seconds']).to be_a(Float)
        expect(config['name']).to be_a(String)
        expect(config['rule']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_rule_group('first', required_attrs)
        synth.grafana_rule_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_rule_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_rule_group,
    method: :grafana_rule_group,
    required_attrs: { folder_uid: 'test-value', interval_seconds: 3.14, name: 'test-value', rule: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_provenance]
end
