# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_stack_service_account_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudStackServiceAccountToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', service_account_id: 'test-value', stack_slug: 'test-value' } }

  describe ':grafana_cloud_stack_service_account_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'test')
        validate_required_attributes(config, [:name, :service_account_id, :stack_slug])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_stack_service_account_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_stack_service_account_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_stack_service_account_token('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_stack_service_account_token.test.id}")
        expect(ref.expiration).to eq("${grafana_cloud_stack_service_account_token.test.expiration}")
        expect(ref.has_expired).to eq("${grafana_cloud_stack_service_account_token.test.has_expired}")
        expect(ref.key).to eq("${grafana_cloud_stack_service_account_token.test.key}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'test')
        expect(config).not_to have_key('expiration')
        expect(config).not_to have_key('has_expired')
        expect(config).not_to have_key('key')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ seconds_to_live: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'full')
        expect(config).to have_key('seconds_to_live')
      end
    end

    context 'optional attributes' do
      it 'includes seconds_to_live when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('opt', required_attrs.merge(seconds_to_live: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'opt')
        expect(config).to have_key('seconds_to_live')
      end

      it 'omits seconds_to_live when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'minimal')
        expect(config).not_to have_key('seconds_to_live')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:key]
        expect(sensitive_fields).to include(:key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_stack_service_account_token', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['service_account_id']).to be_a(String)
        expect(config['stack_slug']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_stack_service_account_token('first', required_attrs)
        synth.grafana_cloud_stack_service_account_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_stack_service_account_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_stack_service_account_token,
    method: :grafana_cloud_stack_service_account_token,
    required_attrs: { name: 'test-value', service_account_id: 'test-value', stack_slug: 'test-value' },
    expected_outputs: [:id, :expiration, :has_expired, :key],
    sensitive_fields: [:key],
    immutable_fields: [],
    boolean_fields: []
end
