# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_org_member resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudOrgMember do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { org: 'test-value', role: 'test-value', user: 'test-value' } }

  describe ':grafana_cloud_org_member' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_org_member('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_org_member', 'test')
        validate_required_attributes(config, [:org, :role, :user])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_org_member('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_org_member)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_org_member('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_org_member.test.id}")
        expect(ref.receive_billing_emails).to eq("${grafana_cloud_org_member.test.receive_billing_emails}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_org_member('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_org_member', 'test')
        expect(config).not_to have_key('receive_billing_emails')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_org_member('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_org_member', 'typed')
        expect(config['org']).to be_a(String)
        expect(config['role']).to be_a(String)
        expect(config['user']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_org_member('first', required_attrs)
        synth.grafana_cloud_org_member('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_org_member')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_org_member,
    method: :grafana_cloud_org_member,
    required_attrs: { org: 'test-value', role: 'test-value', user: 'test-value' },
    expected_outputs: [:id, :receive_billing_emails],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
