# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_machine_learning_holiday resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaMachineLearningHoliday do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':grafana_machine_learning_holiday' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_holiday('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_machine_learning_holiday)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_machine_learning_holiday('test', required_attrs)

        expect(ref.id).to eq("${grafana_machine_learning_holiday.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_periods: [{ 'key1' => 'val1' }], description: 'test-value', ical_timezone: 'test-value', ical_url: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'full')
        expect(config).to have_key('custom_periods')
        expect(config).to have_key('description')
        expect(config).to have_key('ical_timezone')
        expect(config).to have_key('ical_url')
      end
    end

    context 'optional attributes' do
      it 'includes custom_periods when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('opt', required_attrs.merge(custom_periods: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'opt')
        expect(config).to have_key('custom_periods')
      end

      it 'omits custom_periods when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'minimal')
        expect(config).not_to have_key('custom_periods')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes ical_timezone when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('opt', required_attrs.merge(ical_timezone: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'opt')
        expect(config).to have_key('ical_timezone')
      end

      it 'omits ical_timezone when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'minimal')
        expect(config).not_to have_key('ical_timezone')
      end
      it 'includes ical_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('opt', required_attrs.merge(ical_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'opt')
        expect(config).to have_key('ical_url')
      end

      it 'omits ical_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'minimal')
        expect(config).not_to have_key('ical_url')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_machine_learning_holiday', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_machine_learning_holiday('first', required_attrs)
        synth.grafana_machine_learning_holiday('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_machine_learning_holiday')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_machine_learning_holiday,
    method: :grafana_machine_learning_holiday,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
