# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_cloud_provider_aws_resource_metadata_scrape_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaCloudProviderAwsResourceMetadataScrapeJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { aws_account_resource_id: 'test-value', name: 'test-value', stack_id: 'test-value' } }

  describe ':grafana_cloud_provider_aws_resource_metadata_scrape_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'test')
        validate_required_attributes(config, [:aws_account_resource_id, :name, :stack_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_cloud_provider_aws_resource_metadata_scrape_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('test', required_attrs)

        expect(ref.id).to eq("${grafana_cloud_provider_aws_resource_metadata_scrape_job.test.id}")
        expect(ref.disabled_reason).to eq("${grafana_cloud_provider_aws_resource_metadata_scrape_job.test.disabled_reason}")
        expect(ref.enabled).to eq("${grafana_cloud_provider_aws_resource_metadata_scrape_job.test.enabled}")
        expect(ref.regions_subset_override).to eq("${grafana_cloud_provider_aws_resource_metadata_scrape_job.test.regions_subset_override}")
        expect(ref.static_labels).to eq("${grafana_cloud_provider_aws_resource_metadata_scrape_job.test.static_labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'test')
        expect(config).not_to have_key('disabled_reason')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('regions_subset_override')
        expect(config).not_to have_key('static_labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ service: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'full')
        expect(config).to have_key('service')
      end
    end

    context 'optional attributes' do
      it 'includes service when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('opt', required_attrs.merge(service: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'opt')
        expect(config).to have_key('service')
      end

      it 'omits service when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'minimal')
        expect(config).not_to have_key('service')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_cloud_provider_aws_resource_metadata_scrape_job', 'typed')
        expect(config['aws_account_resource_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['stack_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('first', required_attrs)
        synth.grafana_cloud_provider_aws_resource_metadata_scrape_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_cloud_provider_aws_resource_metadata_scrape_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_cloud_provider_aws_resource_metadata_scrape_job,
    method: :grafana_cloud_provider_aws_resource_metadata_scrape_job,
    required_attrs: { aws_account_resource_id: 'test-value', name: 'test-value', stack_id: 'test-value' },
    expected_outputs: [:id, :disabled_reason, :enabled, :regions_subset_override, :static_labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
