# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_annotation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaAnnotation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { text: 'test-value' } }

  describe ':grafana_annotation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_annotation', 'test')
        validate_required_attributes(config, [:text])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_annotation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_annotation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_annotation('test', required_attrs)

        expect(ref.id).to eq("${grafana_annotation.test.id}")
        expect(ref.time).to eq("${grafana_annotation.test.time}")
        expect(ref.time_end).to eq("${grafana_annotation.test.time_end}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_annotation', 'test')
        expect(config).not_to have_key('time')
        expect(config).not_to have_key('time_end')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dashboard_uid: 'test-value', org_id: 'test-value', panel_id: 3.14, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_annotation', 'full')
        expect(config).to have_key('dashboard_uid')
        expect(config).to have_key('org_id')
        expect(config).to have_key('panel_id')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes dashboard_uid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('opt', required_attrs.merge(dashboard_uid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'opt')
        expect(config).to have_key('dashboard_uid')
      end

      it 'omits dashboard_uid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'minimal')
        expect(config).not_to have_key('dashboard_uid')
      end
      it 'includes org_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('opt', required_attrs.merge(org_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'opt')
        expect(config).to have_key('org_id')
      end

      it 'omits org_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'minimal')
        expect(config).not_to have_key('org_id')
      end
      it 'includes panel_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('opt', required_attrs.merge(panel_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'opt')
        expect(config).to have_key('panel_id')
      end

      it 'omits panel_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'minimal')
        expect(config).not_to have_key('panel_id')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_annotation', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_annotation', 'typed')
        expect(config['text']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_annotation('first', required_attrs)
        synth.grafana_annotation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_annotation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_annotation,
    method: :grafana_annotation,
    required_attrs: { text: 'test-value' },
    expected_outputs: [:id, :time, :time_end],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
