# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_synthetic_monitoring_check resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaSyntheticMonitoringCheck do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { job: 'test-value', probes: [3.14], settings: [{ 'key1' => 'val1' }], target: 'test-value' } }

  describe ':grafana_synthetic_monitoring_check' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'test')
        validate_required_attributes(config, [:job, :probes, :settings, :target])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_check('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_synthetic_monitoring_check)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_synthetic_monitoring_check('test', required_attrs)

        expect(ref.id).to eq("${grafana_synthetic_monitoring_check.test.id}")
        expect(ref.tenant_id).to eq("${grafana_synthetic_monitoring_check.test.tenant_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'test')
        expect(config).not_to have_key('tenant_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alert_sensitivity: 'test-value', basic_metrics_only: true, enabled: true, frequency: 3.14, labels: { 'key1' => 'val1' }, timeout: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'full')
        expect(config).to have_key('alert_sensitivity')
        expect(config).to have_key('basic_metrics_only')
        expect(config).to have_key('enabled')
        expect(config).to have_key('frequency')
        expect(config).to have_key('labels')
        expect(config).to have_key('timeout')
      end
    end

    context 'optional attributes' do
      it 'includes alert_sensitivity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(alert_sensitivity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('alert_sensitivity')
      end

      it 'omits alert_sensitivity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('alert_sensitivity')
      end
      it 'includes basic_metrics_only when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(basic_metrics_only: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('basic_metrics_only')
      end

      it 'omits basic_metrics_only when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('basic_metrics_only')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes frequency when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(frequency: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('frequency')
      end

      it 'omits frequency when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('frequency')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('opt', required_attrs.merge(timeout: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'opt')
        expect(config).to have_key('timeout')
      end

      it 'omits timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'minimal')
        expect(config).not_to have_key('timeout')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts basic_metrics_only=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(basic_metrics_only: val)
          synth.grafana_synthetic_monitoring_check("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', "bool_#{val}")
          expect(config['basic_metrics_only']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.grafana_synthetic_monitoring_check("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_synthetic_monitoring_check', 'typed')
        expect(config['job']).to be_a(String)
        expect(config['probes']).to be_a(Array)
        expect(config['settings']).to be_a(Array)
        expect(config['target']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_synthetic_monitoring_check('first', required_attrs)
        synth.grafana_synthetic_monitoring_check('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_synthetic_monitoring_check')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_synthetic_monitoring_check,
    method: :grafana_synthetic_monitoring_check,
    required_attrs: { job: 'test-value', probes: [3.14], settings: [{ 'key1' => 'val1' }], target: 'test-value' },
    expected_outputs: [:id, :tenant_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:basic_metrics_only, :enabled]
end
