# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a grafana_oncall_outgoing_webhook resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GrafanaOncallOutgoingWebhook do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', url: 'test-value' } }

  describe ':grafana_oncall_outgoing_webhook' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'test')
        validate_required_attributes(config, [:name, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_outgoing_webhook('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:grafana_oncall_outgoing_webhook)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.grafana_oncall_outgoing_webhook('test', required_attrs)

        expect(ref.id).to eq("${grafana_oncall_outgoing_webhook.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authorization_header: 'test-value', data: 'test-value', forward_whole_payload: true, headers: 'test-value', http_method: 'test-value', integration_filter: ['test-value'], is_webhook_enabled: true, password: 'test-value', team_id: 'test-value', trigger_template: 'test-value', trigger_type: 'test-value', user: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'full')
        expect(config).to have_key('authorization_header')
        expect(config).to have_key('data')
        expect(config).to have_key('forward_whole_payload')
        expect(config).to have_key('headers')
        expect(config).to have_key('http_method')
        expect(config).to have_key('integration_filter')
        expect(config).to have_key('is_webhook_enabled')
        expect(config).to have_key('password')
        expect(config).to have_key('team_id')
        expect(config).to have_key('trigger_template')
        expect(config).to have_key('trigger_type')
        expect(config).to have_key('user')
      end
    end

    context 'optional attributes' do
      it 'includes authorization_header when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(authorization_header: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('authorization_header')
      end

      it 'omits authorization_header when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('authorization_header')
      end
      it 'includes data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('data')
      end

      it 'omits data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('data')
      end
      it 'includes forward_whole_payload when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(forward_whole_payload: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('forward_whole_payload')
      end

      it 'omits forward_whole_payload when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('forward_whole_payload')
      end
      it 'includes headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(headers: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('headers')
      end

      it 'omits headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('headers')
      end
      it 'includes http_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(http_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('http_method')
      end

      it 'omits http_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('http_method')
      end
      it 'includes integration_filter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(integration_filter: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('integration_filter')
      end

      it 'omits integration_filter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('integration_filter')
      end
      it 'includes is_webhook_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(is_webhook_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('is_webhook_enabled')
      end

      it 'omits is_webhook_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('is_webhook_enabled')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes team_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(team_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('team_id')
      end

      it 'omits team_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('team_id')
      end
      it 'includes trigger_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(trigger_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('trigger_template')
      end

      it 'omits trigger_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('trigger_template')
      end
      it 'includes trigger_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(trigger_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('trigger_type')
      end

      it 'omits trigger_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('trigger_type')
      end
      it 'includes user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('opt', required_attrs.merge(user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'opt')
        expect(config).to have_key('user')
      end

      it 'omits user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'minimal')
        expect(config).not_to have_key('user')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:authorization_header, :password]
        expect(sensitive_fields).to include(:authorization_header)
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts forward_whole_payload=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(forward_whole_payload: val)
          synth.grafana_oncall_outgoing_webhook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', "bool_#{val}")
          expect(config['forward_whole_payload']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_webhook_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_webhook_enabled: val)
          synth.grafana_oncall_outgoing_webhook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', "bool_#{val}")
          expect(config['is_webhook_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'grafana_oncall_outgoing_webhook', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.grafana_oncall_outgoing_webhook('first', required_attrs)
        synth.grafana_oncall_outgoing_webhook('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'grafana_oncall_outgoing_webhook')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :grafana_oncall_outgoing_webhook,
    method: :grafana_oncall_outgoing_webhook,
    required_attrs: { name: 'test-value', url: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:authorization_header, :password],
    immutable_fields: [],
    boolean_fields: [:forward_whole_payload, :is_webhook_enabled]
end
