# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/grafana_frontend_o11y_app/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GrafanaFrontendO11yApp
    include Pangea::Resources::ResourceBuilder

    define_resource :grafana_frontend_o11y_app,
      attributes_class: Grafana::Types::FrontendO11yAppAttributes,
      outputs: { id: :id },
      map: [:allowed_origins, :extra_log_attributes, :name, :settings, :stack_id]
  end
  module Grafana
    include GrafanaFrontendO11yApp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Grafana)
