# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Grafana::Types
  include Dry.Types()

  class FrontendO11yAppAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Grafana::Types

    attribute :allowed_origins, T::Array.of(T::String)
    attribute :extra_log_attributes, T::Hash
    attribute :name, T::String
    attribute :settings, T::Hash
    attribute :stack_id, T::Float
  end
end
